from pathlib import Path
p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:240]!r}')
    s=s.replace(old,new,count)

marker='''    private static final class LeaderEntity implements Entity{\n'''
variable='''    /** Filled geometry for DXF per-segment start/end polyline widths. */\n    private static final class VariableWidth implements Entity{\n        final Entity centerline;final ArrayList<ArrayList<PointF>> outlines=new ArrayList<>();\n        VariableWidth(Entity centerline,double[][] packed){\n            this.centerline=centerline;\n            if(packed!=null)for(double[] polygon:packed){ArrayList<PointF> pts=packedPoints(polygon);if(pts.size()>=3)outlines.add(pts);}\n        }\n        public void bounds(RectF b){\n            if(outlines.isEmpty()){centerline.bounds(b);return;}\n            for(ArrayList<PointF> polygon:outlines)for(PointF q:polygon)add(b,q.x,q.y);\n        }\n        public void draw(Canvas c,Paint p,Matrix m){\n            if(outlines.isEmpty()){centerline.draw(c,p,m);return;}\n            Paint.Style oldStyle=p.getStyle();PathEffect oldEffect=p.getPathEffect();p.setPathEffect(null);p.setStyle(Paint.Style.FILL);\n            for(ArrayList<PointF> polygon:outlines){\n                Path path=new Path();float[] v={polygon.get(0).x,polygon.get(0).y};m.mapPoints(v);path.moveTo(v[0],v[1]);\n                for(int i=1;i<polygon.size();i++){v[0]=polygon.get(i).x;v[1]=polygon.get(i).y;m.mapPoints(v);path.lineTo(v[0],v[1]);}path.close();c.drawPath(path,p);\n            }\n            p.setStyle(oldStyle);p.setPathEffect(oldEffect);\n        }\n    }\n\n'''+marker
repl(marker,variable)

repl('''            if(e instanceof GeometricWidth){drawComplex(c,p,((GeometricWidth)e).entity,m,budget);return;}\n            if(e instanceof LeaderEntity){''','''            if(e instanceof GeometricWidth){drawComplex(c,p,((GeometricWidth)e).entity,m,budget);return;}\n            if(e instanceof VariableWidth){drawComplex(c,p,((VariableWidth)e).centerline,m,budget);return;}\n            if(e instanceof LeaderEntity){''')

repl('''                if(entity instanceof GeometricWidth){entity=((GeometricWidth)entity).entity;continue;}\n                if(entity instanceof Transformed){''','''                if(entity instanceof GeometricWidth){entity=((GeometricWidth)entity).entity;continue;}\n                if(entity instanceof VariableWidth){entity=((VariableWidth)entity).centerline;continue;}\n                if(entity instanceof Transformed){''')

old_lw='''    private static Entity lwPolyline(List<String>a,int from,int to){\n        ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();\n        for(int i=from;i+1<to;i+=2){\n            if(intOf(a.get(i))!=10)continue;\n            float x=floatOf(a.get(i+1));Float y=null;double bulge=0d;int j=i+2;\n            while(j+1<to&&intOf(a.get(j))!=10){\n                int code=intOf(a.get(j));\n                if(code==20)y=floatOf(a.get(j+1));else if(code==42)bulge=floatOf(a.get(j+1));\n                j+=2;\n            }\n            if(y!=null&&Float.isFinite(x)&&Float.isFinite(y)){points.add(new PointF(x,y));bulges.add(bulge);}\n            i=j-2;\n        }\n        if(points.size()<2)return null;\n        Entity result=bulgedPoly(points,bulges,(((int)fv(a,from,to,70,0f))&1)!=0);\n        double width=(has(a,from,to,40)||has(a,from,to,41))?0d:DxfPolylineWidth.constant(fv(a,from,to,43,0f));\n        return geometricWidth(result,width);\n    }\n'''
new_lw='''    private static Entity lwPolyline(List<String>a,int from,int to){\n        ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>(),startWidths=new ArrayList<>(),endWidths=new ArrayList<>();boolean perVertexWidth=false;\n        for(int i=from;i+1<to;i+=2){\n            if(intOf(a.get(i))!=10)continue;\n            float x=floatOf(a.get(i+1));Float y=null;double bulge=0d,startWidth=0d,endWidth=0d;int j=i+2;\n            while(j+1<to&&intOf(a.get(j))!=10){\n                int code=intOf(a.get(j));\n                if(code==20)y=floatOf(a.get(j+1));else if(code==42)bulge=floatOf(a.get(j+1));\n                else if(code==40){startWidth=floatOf(a.get(j+1));perVertexWidth=true;}else if(code==41){endWidth=floatOf(a.get(j+1));perVertexWidth=true;}\n                j+=2;\n            }\n            if(y!=null&&Float.isFinite(x)&&Float.isFinite(y)){points.add(new PointF(x,y));bulges.add(bulge);startWidths.add(startWidth);endWidths.add(endWidth);}\n            i=j-2;\n        }\n        if(points.size()<2)return null;boolean closed=(((int)fv(a,from,to,70,0f))&1)!=0;Entity result=bulgedPoly(points,bulges,closed);\n        if(perVertexWidth)return variableGeometricWidth(result,points,bulges,startWidths,endWidths,closed);\n        return geometricWidth(result,DxfPolylineWidth.constant(fv(a,from,to,43,0f)));\n    }\n'''
repl(old_lw,new_lw)

old_classic='''    private static Entity classicPolyline(DxfBlocks.Record header,List<DxfBlocks.Record> records,List<String> tags)throws IOException{\n        int flags=(int)header.number(70,0);ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();ArrayList<int[]> faces=new ArrayList<>();boolean variableWidth=false;\n        for(DxfBlocks.Record vertex:records){\n            int vf=(int)vertex.number(70,0);\n            if((flags&64)!=0&&(vf&128)!=0&&(vf&64)==0){faces.add(new int[]{(int)vertex.number(71,0),(int)vertex.number(72,0),(int)vertex.number(73,0),(int)vertex.number(74,0)});continue;}\n            if(!has(tags,vertex.from,vertex.to,10)||!has(tags,vertex.from,vertex.to,20))continue;\n            if(has(tags,vertex.from,vertex.to,40)||has(tags,vertex.from,vertex.to,41))variableWidth=true;\n            points.add(new PointF(f(tags,vertex.from,vertex.to,10),f(tags,vertex.from,vertex.to,20)));bulges.add(vertex.number(42,0));\n        }\n        if((flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(points),faces));\n        if((flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(points),(int)header.number(71,0),(int)header.number(72,0),(flags&1)!=0,(flags&32)!=0));\n        Entity result=points.size()<2?null:bulgedPoly(points,bulges,(flags&1)!=0);\n        return variableWidth?result:geometricWidth(result,DxfPolylineWidth.uniform(header.number(40,0),header.number(41,0)));\n    }\n'''
new_classic='''    private static Entity classicPolyline(DxfBlocks.Record header,List<DxfBlocks.Record> records,List<String> tags)throws IOException{\n        int flags=(int)header.number(70,0);ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>(),startWidths=new ArrayList<>(),endWidths=new ArrayList<>();ArrayList<int[]> faces=new ArrayList<>();\n        double defaultStart=header.number(40,0),defaultEnd=header.number(41,0);boolean vertexWidthOverride=false;\n        for(DxfBlocks.Record vertex:records){\n            int vf=(int)vertex.number(70,0);\n            if((flags&64)!=0&&(vf&128)!=0&&(vf&64)==0){faces.add(new int[]{(int)vertex.number(71,0),(int)vertex.number(72,0),(int)vertex.number(73,0),(int)vertex.number(74,0)});continue;}\n            if(!has(tags,vertex.from,vertex.to,10)||!has(tags,vertex.from,vertex.to,20))continue;\n            boolean hasStart=has(tags,vertex.from,vertex.to,40),hasEnd=has(tags,vertex.from,vertex.to,41);if(hasStart||hasEnd)vertexWidthOverride=true;\n            points.add(new PointF(f(tags,vertex.from,vertex.to,10),f(tags,vertex.from,vertex.to,20)));bulges.add(vertex.number(42,0));\n            startWidths.add(hasStart?vertex.number(40,defaultStart):defaultStart);endWidths.add(hasEnd?vertex.number(41,defaultEnd):defaultEnd);\n        }\n        if((flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(points),faces));\n        if((flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(points),(int)header.number(71,0),(int)header.number(72,0),(flags&1)!=0,(flags&32)!=0));\n        boolean closed=(flags&1)!=0;Entity result=points.size()<2?null:bulgedPoly(points,bulges,closed);double uniform=DxfPolylineWidth.uniform(defaultStart,defaultEnd);\n        if(!vertexWidthOverride&&uniform>1e-12)return geometricWidth(result,uniform);\n        return variableGeometricWidth(result,points,bulges,startWidths,endWidths,closed);\n    }\n'''
repl(old_classic,new_classic)

old_pending='''    private static final class PendingPoly {\n        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int flags,mCount,nCount,aci,trueColor,lineWeight;final double lineTypeScale,geometricWidth;final long transparencyRaw;\n        final double[] ocs;boolean variableWidth;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>();final ArrayList<int[]> faces=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,int flags,int mCount,int nCount,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double geometricWidth,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.flags=flags;this.mCount=mCount;this.nCount=nCount;this.closed=(flags&1)!=0;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.geometricWidth=geometricWidth;this.ocs=ocs;\n        }\n    }\n'''
new_pending='''    private static final class PendingPoly {\n        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int flags,mCount,nCount,aci,trueColor,lineWeight;final double lineTypeScale,geometricWidth,defaultStartWidth,defaultEndWidth;final long transparencyRaw;\n        final double[] ocs;boolean variableWidth;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>(),startWidths=new ArrayList<>(),endWidths=new ArrayList<>();final ArrayList<int[]> faces=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,int flags,int mCount,int nCount,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double defaultStartWidth,double defaultEndWidth,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.flags=flags;this.mCount=mCount;this.nCount=nCount;this.closed=(flags&1)!=0;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.defaultStartWidth=defaultStartWidth;this.defaultEndWidth=defaultEndWidth;this.geometricWidth=DxfPolylineWidth.uniform(defaultStartWidth,defaultEndWidth);this.ocs=ocs;\n        }\n    }\n'''
repl(old_pending,new_pending)

repl('''                        if(has(r.tags,0,r.tags.size(),40)||has(r.tags,0,r.tags.size(),41))c.pending.variableWidth=true;\n                        c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));\n''','''                        boolean hasStart=has(r.tags,0,r.tags.size(),40),hasEnd=has(r.tags,0,r.tags.size(),41);if(hasStart||hasEnd)c.pending.variableWidth=true;\n                        c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));\n                        c.pending.startWidths.add(r.number(40,c.pending.defaultStartWidth));c.pending.endWidths.add(r.number(41,c.pending.defaultEndWidth));\n''')

repl('''                DxfPolylineWidth.uniform(r.number(40,0),r.number(41,0)),ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n''','''                r.number(40,0),r.number(41,0),ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n''')

old_stream='''    private static Entity streamPolyline(PendingPoly p){\n        if((p.flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(p.points),p.faces));\n        if((p.flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(p.points),p.mCount,p.nCount,(p.flags&1)!=0,(p.flags&32)!=0));\n        Entity result=p.points.size()<2?null:bulgedPoly(p.points,p.bulges,p.closed);\n        return p.variableWidth?result:geometricWidth(result,p.geometricWidth);\n    }\n\n    private static Entity geometricWidth(Entity entity,double width){return entity!=null&&DxfPolylineWidth.constant(width)>1e-12?new GeometricWidth(entity,width):entity;}\n'''
new_stream='''    private static Entity streamPolyline(PendingPoly p){\n        if((p.flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(p.points),p.faces));\n        if((p.flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(p.points),p.mCount,p.nCount,(p.flags&1)!=0,(p.flags&32)!=0));\n        Entity result=p.points.size()<2?null:bulgedPoly(p.points,p.bulges,p.closed);\n        if(!p.variableWidth&&p.geometricWidth>1e-12)return geometricWidth(result,p.geometricWidth);\n        return variableGeometricWidth(result,p.points,p.bulges,p.startWidths,p.endWidths,p.closed);\n    }\n\n    private static Entity variableGeometricWidth(Entity entity,List<PointF> points,List<Double> bulges,List<Double> startWidths,List<Double> endWidths,boolean closed){\n        if(entity==null||points==null||points.size()<2)return entity;int n=points.size();double[] xs=new double[n],ys=new double[n],bs=new double[n],sw=new double[n],ew=new double[n];\n        for(int i=0;i<n;i++){PointF q=points.get(i);xs[i]=q.x;ys[i]=q.y;bs[i]=bulges!=null&&i<bulges.size()?bulges.get(i):0d;sw[i]=startWidths!=null&&i<startWidths.size()?startWidths.get(i):0d;ew[i]=endWidths!=null&&i<endWidths.size()?endWidths.get(i):0d;}\n        double[][] outlines=DxfPolylineWidth.variable(xs,ys,bs,sw,ew,closed);return outlines.length==0?entity:new VariableWidth(entity,outlines);\n    }\n\n    private static Entity geometricWidth(Entity entity,double width){return entity!=null&&DxfPolylineWidth.constant(width)>1e-12?new GeometricWidth(entity,width):entity;}\n'''
repl(old_stream,new_stream)

p.write_text(s)
