from pathlib import Path

p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:220]!r}')
    s=s.replace(old,new,count)

poly='''    private static final class Poly implements Entity{\n        final ArrayList<PointF> pts;final boolean closed;\n        Poly(ArrayList<PointF>p,boolean c){pts=p;closed=c;}\n        public void bounds(RectF b){for(PointF p:pts)add(b,p.x,p.y);}\n        public void draw(Canvas c,Paint p,Matrix m){\n            if(pts.size()<2)return;\n            Path q=new Path();float[]v={pts.get(0).x,pts.get(0).y};m.mapPoints(v);q.moveTo(v[0],v[1]);\n            for(int i=1;i<pts.size();i++){v[0]=pts.get(i).x;v[1]=pts.get(i).y;m.mapPoints(v);q.lineTo(v[0],v[1]);}\n            if(closed)q.close();c.drawPath(q,p);\n        }\n    }\n\n'''
wide=poly+'''    /** Applies DXF geometric polyline width in drawing units without changing entity lineweight semantics. */\n    private static final class GeometricWidth implements Entity{\n        final Entity entity;final double width;\n        GeometricWidth(Entity entity,double width){this.entity=entity;this.width=DxfPolylineWidth.constant(width);}\n        public void bounds(RectF b){\n            RectF local=new RectF(Float.MAX_VALUE,Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE);entity.bounds(local);\n            if(local.left>local.right||local.top>local.bottom)return;float h=(float)(width*.5);\n            add(b,local.left-h,local.top-h);add(b,local.right+h,local.bottom+h);\n        }\n        public void draw(Canvas c,Paint p,Matrix m){\n            float[] basis={1,0,0,1};m.mapVectors(basis);double sx=Math.hypot(basis[0],basis[1]),sy=Math.hypot(basis[2],basis[3]);\n            double device=DxfPolylineWidth.device(width,sx,sy);if(device<=0){entity.draw(c,p,m);return;}\n            float oldWidth=p.getStrokeWidth();Paint.Cap oldCap=p.getStrokeCap();Paint.Join oldJoin=p.getStrokeJoin();\n            p.setStrokeWidth((float)device);p.setStrokeCap(Paint.Cap.BUTT);p.setStrokeJoin(Paint.Join.MITER);entity.draw(c,p,m);\n            p.setStrokeWidth(oldWidth);p.setStrokeCap(oldCap);p.setStrokeJoin(oldJoin);\n        }\n    }\n\n'''
repl(poly,wide)

repl('''            if(e==null||budget[0]<=0)return;\n            if(e instanceof Transformed){Transformed t=(Transformed)e;Matrix q=new Matrix();q.setConcat(m,t.matrix);drawComplex(c,p,t.entity,q,budget);return;}\n''','''            if(e==null||budget[0]<=0)return;\n            if(e instanceof GeometricWidth){drawComplex(c,p,((GeometricWidth)e).entity,m,budget);return;}\n            if(e instanceof Transformed){Transformed t=(Transformed)e;Matrix q=new Matrix();q.setConcat(m,t.matrix);drawComplex(c,p,t.entity,q,budget);return;}\n''')

repl('''            while(true){\n                if(entity instanceof Transformed){\n''','''            while(true){\n                if(entity instanceof GeometricWidth){entity=((GeometricWidth)entity).entity;continue;}\n                if(entity instanceof Transformed){\n''')

repl('''        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int flags,mCount,nCount,aci,trueColor,lineWeight;final double lineTypeScale;final long transparencyRaw;\n        final double[] ocs;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>();final ArrayList<int[]> faces=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,int flags,int mCount,int nCount,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.flags=flags;this.mCount=mCount;this.nCount=nCount;this.closed=(flags&1)!=0;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.ocs=ocs;\n        }\n''','''        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int flags,mCount,nCount,aci,trueColor,lineWeight;final double lineTypeScale,geometricWidth;final long transparencyRaw;\n        final double[] ocs;boolean variableWidth;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>();final ArrayList<int[]> faces=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,int flags,int mCount,int nCount,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double geometricWidth,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.flags=flags;this.mCount=mCount;this.nCount=nCount;this.closed=(flags&1)!=0;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.geometricWidth=geometricWidth;this.ocs=ocs;\n        }\n''')

repl('''                    }else{\n                        c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));\n                    }\n''','''                    }else{\n                        if(has(r.tags,0,r.tags.size(),40)||has(r.tags,0,r.tags.size(),41))c.pending.variableWidth=true;\n                        c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));\n                    }\n''')

repl('''            c.pending=new PendingPoly(target,r.text(8,"0"),r.text(5,""),flags,r.integer(71,0),r.integer(72,0),\n                r.integer(62,DxfColor.BYLAYER),r.trueColor(),r.longInteger(440,DxfTransparency.UNSET),r.text(6,DxfStyle.BYLAYER),r.integer(370,DxfStyle.LW_BYLAYER),DxfStyle.saneScale(r.number(48,1)),\n                ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n''','''            c.pending=new PendingPoly(target,r.text(8,"0"),r.text(5,""),flags,r.integer(71,0),r.integer(72,0),\n                r.integer(62,DxfColor.BYLAYER),r.trueColor(),r.longInteger(440,DxfTransparency.UNSET),r.text(6,DxfStyle.BYLAYER),r.integer(370,DxfStyle.LW_BYLAYER),DxfStyle.saneScale(r.number(48,1)),\n                DxfPolylineWidth.uniform(r.number(40,0),r.number(41,0)),ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n''')

repl('''        if(points.size()<2)return null;\n        return bulgedPoly(points,bulges,(((int)fv(a,from,to,70,0f))&1)!=0);\n    }\n\n    private static Entity splineEntity''','''        if(points.size()<2)return null;\n        Entity result=bulgedPoly(points,bulges,(((int)fv(a,from,to,70,0f))&1)!=0);\n        double width=(has(a,from,to,40)||has(a,from,to,41))?0d:DxfPolylineWidth.constant(fv(a,from,to,43,0f));\n        return geometricWidth(result,width);\n    }\n\n    private static Entity splineEntity''')

old_classic='''    private static Entity classicPolyline(DxfBlocks.Record header,List<DxfBlocks.Record> records,List<String> tags)throws IOException{\n        int flags=(int)header.number(70,0);ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();ArrayList<int[]> faces=new ArrayList<>();\n        for(DxfBlocks.Record vertex:records){\n            int vf=(int)vertex.number(70,0);\n            if((flags&64)!=0&&(vf&128)!=0&&(vf&64)==0){faces.add(new int[]{(int)vertex.number(71,0),(int)vertex.number(72,0),(int)vertex.number(73,0),(int)vertex.number(74,0)});continue;}\n            if(!has(tags,vertex.from,vertex.to,10)||!has(tags,vertex.from,vertex.to,20))continue;\n            points.add(new PointF(f(tags,vertex.from,vertex.to,10),f(tags,vertex.from,vertex.to,20)));bulges.add(vertex.number(42,0));\n        }\n        if((flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(points),faces));\n        if((flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(points),(int)header.number(71,0),(int)header.number(72,0),(flags&1)!=0,(flags&32)!=0));\n        return points.size()<2?null:bulgedPoly(points,bulges,(flags&1)!=0);\n    }\n\n    private static Entity streamPolyline(PendingPoly p){\n        if((p.flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(p.points),p.faces));\n        if((p.flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(p.points),p.mCount,p.nCount,(p.flags&1)!=0,(p.flags&32)!=0));\n        return p.points.size()<2?null:bulgedPoly(p.points,p.bulges,p.closed);\n    }\n\n    private static Entity segmentSet(double[] packed){return packed!=null&&packed.length>=4?new SegmentSet(packed):null;}\n'''
new_classic='''    private static Entity classicPolyline(DxfBlocks.Record header,List<DxfBlocks.Record> records,List<String> tags)throws IOException{\n        int flags=(int)header.number(70,0);ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();ArrayList<int[]> faces=new ArrayList<>();boolean variableWidth=false;\n        for(DxfBlocks.Record vertex:records){\n            int vf=(int)vertex.number(70,0);\n            if((flags&64)!=0&&(vf&128)!=0&&(vf&64)==0){faces.add(new int[]{(int)vertex.number(71,0),(int)vertex.number(72,0),(int)vertex.number(73,0),(int)vertex.number(74,0)});continue;}\n            if(!has(tags,vertex.from,vertex.to,10)||!has(tags,vertex.from,vertex.to,20))continue;\n            if(has(tags,vertex.from,vertex.to,40)||has(tags,vertex.from,vertex.to,41))variableWidth=true;\n            points.add(new PointF(f(tags,vertex.from,vertex.to,10),f(tags,vertex.from,vertex.to,20)));bulges.add(vertex.number(42,0));\n        }\n        if((flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(points),faces));\n        if((flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(points),(int)header.number(71,0),(int)header.number(72,0),(flags&1)!=0,(flags&32)!=0));\n        Entity result=points.size()<2?null:bulgedPoly(points,bulges,(flags&1)!=0);\n        return variableWidth?result:geometricWidth(result,DxfPolylineWidth.uniform(header.number(40,0),header.number(41,0)));\n    }\n\n    private static Entity streamPolyline(PendingPoly p){\n        if((p.flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(p.points),p.faces));\n        if((p.flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(p.points),p.mCount,p.nCount,(p.flags&1)!=0,(p.flags&32)!=0));\n        Entity result=p.points.size()<2?null:bulgedPoly(p.points,p.bulges,p.closed);\n        return p.variableWidth?result:geometricWidth(result,p.geometricWidth);\n    }\n\n    private static Entity geometricWidth(Entity entity,double width){return entity!=null&&DxfPolylineWidth.constant(width)>1e-12?new GeometricWidth(entity,width):entity;}\n    private static Entity segmentSet(double[] packed){return packed!=null&&packed.length>=4?new SegmentSet(packed):null;}\n'''
repl(old_classic,new_classic)

p.write_text(s)
