from pathlib import Path
p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:240]!r}')
    s=s.replace(old,new,count)

repl('''        final ArrayList<HatchLoop> loops;final boolean solid;final int style;\n        final ArrayList<DxfHatchPattern.Line> pattern;final DxfHatchGradient.Data gradient;\n        Hatch(ArrayList<HatchLoop> loops,boolean solid,int style,ArrayList<DxfHatchPattern.Line> pattern,DxfHatchGradient.Data gradient){\n            this.loops=loops;this.solid=solid;this.style=style;this.pattern=pattern;this.gradient=gradient==null?DxfHatchGradient.none():gradient;\n        }\n''','''        final ArrayList<HatchLoop> loops;final boolean solid;final int style,solidFillAci;\n        final ArrayList<DxfHatchPattern.Line> pattern;final DxfHatchGradient.Data gradient;\n        Hatch(ArrayList<HatchLoop> loops,boolean solid,int style,ArrayList<DxfHatchPattern.Line> pattern,DxfHatchGradient.Data gradient){\n            this(loops,solid,style,pattern,gradient,-1);\n        }\n        Hatch(ArrayList<HatchLoop> loops,boolean solid,int style,ArrayList<DxfHatchPattern.Line> pattern,DxfHatchGradient.Data gradient,int solidFillAci){\n            this.loops=loops;this.solid=solid;this.style=style;this.pattern=pattern;this.gradient=gradient==null?DxfHatchGradient.none():gradient;this.solidFillAci=solidFillAci;\n        }\n''')

repl('''            if(solid){\n                p.setPathEffect(null);p.setStyle(Paint.Style.FILL);c.drawPath(clip,p);\n                p.setStyle(oldStyle);p.setPathEffect(oldEffect);return;\n            }\n''','''            if(solid){\n                int oldColor=p.getColor();p.setPathEffect(null);p.setStyle(Paint.Style.FILL);\n                if(solidFillAci>=0)p.setColor(DxfMPolygon.solidFillArgb(solidFillAci,oldColor));c.drawPath(clip,p);p.setColor(oldColor);\n                p.setStyle(oldStyle);p.setPathEffect(oldEffect);return;\n            }\n''')

repl('''            "CIRCLE".equals(type)||"ARC".equals(type)||"LWPOLYLINE".equals(type)||"POLYLINE".equals(type)||\n            "HATCH".equals(type)||"SOLID".equals(type)||"TRACE".equals(type);\n''','''            "CIRCLE".equals(type)||"ARC".equals(type)||"LWPOLYLINE".equals(type)||"POLYLINE".equals(type)||\n            "HATCH".equals(type)||"MPOLYGON".equals(type)||"SOLID".equals(type)||"TRACE".equals(type);\n''')

repl('''        if("HATCH".equals(type))return parseHatch(a,from,to);\n        if("WIPEOUT".equals(type))return parseWipeout(a,from,to);\n''','''        if("HATCH".equals(type))return parseHatch(a,from,to);\n        if("MPOLYGON".equals(type))return parseMPolygon(a,from,to);\n        if("WIPEOUT".equals(type))return parseWipeout(a,from,to);\n''')

repl('''    private static Entity parseHatch(List<String>a,int from,int to){\n        int pathCount=(int)fv(a,from,to,91,0f);if(pathCount<=0)return null;\n''','''    private static Entity parseHatch(List<String>a,int from,int to){return parseHatchLike(a,from,to,false);}\n    private static Entity parseMPolygon(List<String>a,int from,int to){return parseHatchLike(a,from,to,true);}\n\n    private static Entity parseHatchLike(List<String>a,int from,int to,boolean mpolygon){\n        int pathCount=(int)fv(a,from,to,91,0f);if(pathCount<=0)return null;\n''')

repl('''        if(loops.isEmpty())return null;\n        boolean solid=((int)fv(a,from,to,70,0f))!=0;int style=(int)fv(a,from,to,75,0f);\n        DxfHatchGradient.Data gradient=DxfHatchGradient.parse(a,from,to);\n        ArrayList<DxfHatchPattern.Line> pattern=(solid||gradient.enabled)?new ArrayList<>():parseHatchPatternLines(a,i,to);\n        return new Hatch(loops,solid,style,pattern,gradient);\n    }\n''','''        if(loops.isEmpty())return null;\n        if(mpolygon){\n            double ox=fv(a,i,to,11,0f),oy=fv(a,i,to,21,0f);\n            if(Double.isFinite(ox)&&Double.isFinite(oy)&&(Math.abs(ox)>1e-12||Math.abs(oy)>1e-12))\n                for(HatchLoop loop:loops)for(PointF q:loop.points){q.x+=ox;q.y+=oy;}\n        }\n        boolean solid=mpolygon?DxfMPolygon.solid((int)fv(a,from,to,71,0f)):((int)fv(a,from,to,70,0f))!=0;\n        int style=mpolygon?0:(int)fv(a,from,to,75,0f);DxfHatchGradient.Data gradient=DxfHatchGradient.parse(a,from,to);\n        ArrayList<DxfHatchPattern.Line> pattern=(solid||gradient.enabled)?new ArrayList<>():parseHatchPatternLines(a,i,to);\n        int fillAci=mpolygon?(int)fv(a,i,to,63,256f):-1;Hatch fill=new Hatch(loops,solid,style,pattern,gradient,fillAci);\n        if(!mpolygon)return fill;\n        ArrayList<Entity> items=new ArrayList<>();if(solid||gradient.enabled||!pattern.isEmpty())items.add(fill);\n        for(HatchLoop loop:loops)if(loop.points.size()>=2)items.add(new Poly(new ArrayList<>(loop.points),true));\n        if(items.isEmpty())return null;return items.size()==1?items.get(0):new Composite(items);\n    }\n''')

repl('''return code==1||code==2||code==3||code==4||code==5||code==6||code==7||code==8||code==9||code==60||code==62||code==66||code==67||code==68||code==69||\n''','''return code==1||code==2||code==3||code==4||code==5||code==6||code==7||code==8||code==9||code==60||code==62||code==63||code==66||code==67||code==68||code==69||\n''')

p.write_text(s)
