from pathlib import Path
p=Path('app/src/main/java/com/musa/cad/DxfParser.java')
s=p.read_text()

def rep(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:180]!r}')
    s=s.replace(old,new,count)

rep('''    private static final class StreamInsert implements StreamNode {\n''','''    private static final class StreamViewport implements StreamNode {\n        final DxfViewport.Spec spec;final String layer,lineType,handle;final int aci,trueColor,lineWeight;final long transparencyRaw;final double lineTypeScale;\n        StreamViewport(StreamRecord r)throws IOException{\n            spec=DxfViewport.of(r.number(10,0),r.number(20,0),r.number(40,0),r.number(41,0),\n                r.number(12,0),r.number(22,0),r.number(45,0),r.number(51,0),r.integer(69,0),r.integer(68,1),\n                r.number(16,0),r.number(26,0),r.number(36,1));\n            layer=r.text(8,"0");handle=r.text(5,"");aci=r.integer(62,DxfColor.BYLAYER);trueColor=r.trueColor();\n            transparencyRaw=r.longInteger(440,DxfTransparency.UNSET);lineType=r.text(6,DxfStyle.BYLAYER);\n            lineWeight=r.integer(370,DxfStyle.LW_BYLAYER);lineTypeScale=DxfStyle.saneScale(r.number(48,1));\n        }\n    }\n\n    private static final class StreamInsert implements StreamNode {\n''')

rep('''        String activeLayout=DxfSpace.chooseActive(context.rootsByLayout,preferredLayout);\n        ArrayList<StreamNode> roots=context.rootsByLayout.get(activeLayout);if(roots==null)roots=new ArrayList<>();\n        if(!context.drawOrder.isEmpty())roots.sort((a,b)->DxfDrawOrder.compare(streamHandle(a),streamHandle(b),context.drawOrder));\n        StreamCounter counter=new StreamCounter();\n        expandStream(roots,new DxfBlocks.Transform(),"0",null,null,null,DxfStyle.LW_BYLAYER,\n            context.blocks,new HashSet<>(),entities,layers,visibleLayers,counter,context);\n''','''        String activeLayout=DxfSpace.chooseActive(context.rootsByLayout,preferredLayout);\n        List<LayerEntity> viewportModel=null;\n        if(!DxfSpace.isModel(activeLayout)){\n            ArrayList<StreamNode> modelRoots=context.rootsByLayout.get(DxfSpace.MODEL);\n            if(modelRoots!=null&&!modelRoots.isEmpty()){\n                ArrayList<StreamNode> orderedModel=new ArrayList<>(modelRoots);\n                if(!context.drawOrder.isEmpty())orderedModel.sort((a,b)->DxfDrawOrder.compare(streamHandle(a),streamHandle(b),context.drawOrder));\n                ArrayList<Entity> modelRaw=new ArrayList<>();int previousSkipped=context.skipped;StreamCounter modelCounter=new StreamCounter();\n                expandStream(orderedModel,new DxfBlocks.Transform(),"0",null,null,null,DxfStyle.LW_BYLAYER,\n                    context.blocks,new HashSet<>(),modelRaw,layers,visibleLayers,modelCounter,context,null);\n                context.skipped=previousSkipped;viewportModel=new ArrayList<>();\n                for(Entity e:modelRaw)if(e instanceof LayerEntity)viewportModel.add((LayerEntity)e);\n            }\n        }\n        ArrayList<StreamNode> roots=context.rootsByLayout.get(activeLayout);if(roots==null)roots=new ArrayList<>();\n        if(!context.drawOrder.isEmpty())roots.sort((a,b)->DxfDrawOrder.compare(streamHandle(a),streamHandle(b),context.drawOrder));\n        StreamCounter counter=new StreamCounter();\n        expandStream(roots,new DxfBlocks.Transform(),"0",null,null,null,DxfStyle.LW_BYLAYER,\n            context.blocks,new HashSet<>(),entities,layers,visibleLayers,counter,context,viewportModel);\n''')

rep('''        return code==1||code==2||code==3||code==4||code==5||code==6||code==7||code==8||code==9||code==62||code==66||code==67||\n''','''        return code==1||code==2||code==3||code==4||code==5||code==6||code==7||code==8||code==9||code==62||code==66||code==67||code==68||code==69||\n''')

rep('''        if("INSERT".equals(type)){target.add(new StreamInsert(r));return;}\n''','''        if("VIEWPORT".equals(type)){target.add(new StreamViewport(r));return;}\n        if("INSERT".equals(type)){target.add(new StreamInsert(r));return;}\n''')

rep('''                                     DxfTransparency.Ref byBlockTransparency,String byBlockLineType,int byBlockLineWeight,Map<String,StreamBlock> blocks,Set<String> stack,ArrayList<Entity> entities,Set<String> layers,\n                                     Set<String> visibleLayers,StreamCounter counter,StreamContext context)throws IOException{\n''','''                                     DxfTransparency.Ref byBlockTransparency,String byBlockLineType,int byBlockLineWeight,Map<String,StreamBlock> blocks,Set<String> stack,ArrayList<Entity> entities,Set<String> layers,\n                                     Set<String> visibleLayers,StreamCounter counter,StreamContext context,List<LayerEntity> viewportModel)throws IOException{\n''')

needle='''            if(node instanceof StreamDimension){\n'''
insert='''            if(node instanceof StreamViewport){\n                StreamViewport viewport=(StreamViewport)node;String layer="0".equals(viewport.layer)?parentLayer:viewport.layer;\n                if(viewportModel==null||!viewport.spec.supported()){context.skipped++;continue;}\n                appendViewportEntities(entities,viewportModel,viewport.spec);\n                DxfColor.Ref ref=DxfColor.resolve(viewport.aci,viewport.trueColor,layer,byBlockColor);\n                DxfTransparency.Ref transparency=DxfTransparency.resolve(viewport.transparencyRaw,layer,byBlockTransparency);\n                int color=DxfTransparency.apply(DxfColor.argb(ref,context.layerTable.colors),DxfTransparency.opacity(transparency,context.layerTable.opacities));\n                String semanticType=DxfStyle.resolveLineType(viewport.lineType,byBlockLineType);\n                int semanticWeight=DxfStyle.resolveLineWeight(viewport.lineWeight,byBlockLineWeight);\n                String effectiveType=DxfStyle.effectiveLineType(semanticType,layer,context.layerTable.lineTypes);\n                int effectiveWeight=DxfStyle.effectiveLineWeight(semanticWeight,layer,context.layerTable.lineWeights);\n                entities.add(new LayerEntity(new Transformed(viewportFrame(viewport.spec),parent),layer,color,effectiveWeight,\n                    context.lineTypes.get(effectiveType),viewport.lineTypeScale*context.lineTypes.globalScale));\n                if(layers.add(layer)&&!context.layerTable.contains(layer))visibleLayers.add(layer);\n                continue;\n            }\n'''
if s.count(needle)!=1: raise SystemExit('dimension marker mismatch')
s=s.replace(needle,insert+needle,1)

rep('''                expandStream(block.members,parent,layer,dimColor,dimTransparency,dimType,dimWeight,blocks,stack,entities,layers,visibleLayers,counter,context);\n''','''                expandStream(block.members,parent,layer,dimColor,dimTransparency,dimType,dimWeight,blocks,stack,entities,layers,visibleLayers,counter,context,viewportModel);\n''')
rep('''                    expandStream(block.members,transform,layer,insertColor,insertTransparency,insertType,insertWeight,blocks,stack,entities,layers,visibleLayers,counter,context);\n''','''                    expandStream(block.members,transform,layer,insertColor,insertTransparency,insertType,insertWeight,blocks,stack,entities,layers,visibleLayers,counter,context,viewportModel);\n''')

rep('''        if(node instanceof StreamShape)return ((StreamShape)node).handle;\n        if(node instanceof StreamInsert)return ((StreamInsert)node).handle;\n''','''        if(node instanceof StreamShape)return ((StreamShape)node).handle;\n        if(node instanceof StreamViewport)return ((StreamViewport)node).handle;\n        if(node instanceof StreamInsert)return ((StreamInsert)node).handle;\n''')

p.write_text(s)
