from pathlib import Path

p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:180]!r}')
    s=s.replace(old,new,count)

repl('''    private static final class FilledPoly implements Entity{\n''','''    private static final class SegmentSet implements Entity{\n        final float[] xy;\n        SegmentSet(double[] packed){xy=new float[packed==null?0:packed.length];for(int i=0;i<xy.length;i++)xy[i]=(float)packed[i];}\n        public void bounds(RectF b){for(int i=0;i+1<xy.length;i+=2)add(b,xy[i],xy[i+1]);}\n        public void draw(Canvas c,Paint p,Matrix m){if(xy.length<4)return;float[] v=xy.clone();m.mapPoints(v);c.drawLines(v,p);}\n    }\n\n    private static final class FilledPoly implements Entity{\n''')

repl('''            }else if("POLYLINE".equals(item.record.type)){\n                ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();int j=index+1;\n                while(j<placements.size()&&"VERTEX".equals(placements.get(j).record.type)){\n                    DxfBlocks.Record vertex=placements.get(j).record;\n                    points.add(new PointF(f(lines,vertex.from,vertex.to,10),f(lines,vertex.from,vertex.to,20)));\n                    bulges.add(vertex.number(42,0));j++;\n                }\n                if(points.size()<2){skipped++;continue;}\n                entity=bulgedPoly(points,bulges,(((int)item.record.number(70,0))&1)!=0);index=j-1;\n''','''            }else if("POLYLINE".equals(item.record.type)){\n                ArrayList<DxfBlocks.Record> vertices=new ArrayList<>();int j=index+1;\n                while(j<placements.size()&&"VERTEX".equals(placements.get(j).record.type)){vertices.add(placements.get(j).record);j++;}\n                entity=classicPolyline(item.record,vertices,lines);index=j-1;\n                if(entity==null){skipped++;continue;}\n''')

repl('''    private static final class PendingPoly {\n        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int aci,trueColor,lineWeight;final double lineTypeScale;final long transparencyRaw;\n        final double[] ocs;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,boolean closed,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.closed=closed;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.ocs=ocs;\n        }\n    }\n''','''    private static final class PendingPoly {\n        final ArrayList<StreamNode> target;final String layer,lineType,handle;final boolean closed;final int flags,mCount,nCount,aci,trueColor,lineWeight;final double lineTypeScale;final long transparencyRaw;\n        final double[] ocs;\n        final ArrayList<PointF> points=new ArrayList<>();final ArrayList<Double> bulges=new ArrayList<>();final ArrayList<int[]> faces=new ArrayList<>();\n        PendingPoly(ArrayList<StreamNode> target,String layer,String handle,int flags,int mCount,int nCount,int aci,int trueColor,long transparencyRaw,String lineType,int lineWeight,double lineTypeScale,double[] ocs){\n            this.target=target;this.layer=layer;this.handle=handle;this.flags=flags;this.mCount=mCount;this.nCount=nCount;this.closed=(flags&1)!=0;this.aci=aci;this.trueColor=trueColor;this.transparencyRaw=transparencyRaw;\n            this.lineType=lineType;this.lineWeight=lineWeight;this.lineTypeScale=lineTypeScale;this.ocs=ocs;\n        }\n    }\n''')

repl('''            if("VERTEX".equals(type)){\n                if(!DxfVisibility.invisible(type,r.integer(60,0),r.integer(70,0))){c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));}\n                return;\n            }\n''','''            if("VERTEX".equals(type)){\n                if(!DxfVisibility.invisible(type,r.integer(60,0),r.integer(70,0))){\n                    int vertexFlags=r.integer(70,0);\n                    if((c.pending.flags&64)!=0&&(vertexFlags&128)!=0&&(vertexFlags&64)==0){\n                        c.pending.faces.add(new int[]{r.integer(71,0),r.integer(72,0),r.integer(73,0),r.integer(74,0)});\n                    }else{\n                        c.pending.points.add(new PointF((float)r.number(10,0),(float)r.number(20,0)));c.pending.bulges.add(r.number(42,0));\n                    }\n                }\n                return;\n            }\n''')

repl('''        if("POLYLINE".equals(type)){\n            c.pending=new PendingPoly(target,r.text(8,"0"),r.text(5,""),(((int)r.number(70,0))&1)!=0,\n                r.integer(62,DxfColor.BYLAYER),r.trueColor(),r.longInteger(440,DxfTransparency.UNSET),r.text(6,DxfStyle.BYLAYER),r.integer(370,DxfStyle.LW_BYLAYER),DxfStyle.saneScale(r.number(48,1)),\n                ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n        }\n''','''        if("POLYLINE".equals(type)){\n            int flags=r.integer(70,0);\n            c.pending=new PendingPoly(target,r.text(8,"0"),r.text(5,""),flags,r.integer(71,0),r.integer(72,0),\n                r.integer(62,DxfColor.BYLAYER),r.trueColor(),r.longInteger(440,DxfTransparency.UNSET),r.text(6,DxfStyle.BYLAYER),r.integer(370,DxfStyle.LW_BYLAYER),DxfStyle.saneScale(r.number(48,1)),\n                ocsMatrix("POLYLINE",r.tags,0,r.tags.size()));return;\n        }\n''')

repl('''    private static void finishPending(StreamContext c)throws IOException{\n        PendingPoly p=c.pending;if(p==null)return;c.pending=null;\n        if(p.points.size()<2){c.skipped++;return;}\n        Entity entity=bulgedPoly(p.points,p.bulges,p.closed);\n        if(p.ocs!=null)entity=new Transformed(entity,p.ocs);\n        p.target.add(new StreamShape(entity,p.layer,p.handle,p.aci,p.trueColor,p.transparencyRaw,p.lineType,p.lineWeight,p.lineTypeScale));\n    }\n''','''    private static void finishPending(StreamContext c)throws IOException{\n        PendingPoly p=c.pending;if(p==null)return;c.pending=null;\n        Entity entity=streamPolyline(p);if(entity==null){c.skipped++;return;}\n        if(p.ocs!=null)entity=new Transformed(entity,p.ocs);\n        p.target.add(new StreamShape(entity,p.layer,p.handle,p.aci,p.trueColor,p.transparencyRaw,p.lineType,p.lineWeight,p.lineTypeScale));\n    }\n''')

repl('''            }else if(entity instanceof FilledPoly){\n                FilledPoly poly=(FilledPoly)entity;double[] xy=new double[poly.pts.size()*2];\n                for(int i=0;i<poly.pts.size();i++){xy[i*2]=poly.pts.get(i).x;xy[i*2+1]=poly.pts.get(i).y;}\n                candidates=DxfSnapGeometry.poly(xy,true);\n            }\n''','''            }else if(entity instanceof FilledPoly){\n                FilledPoly poly=(FilledPoly)entity;double[] xy=new double[poly.pts.size()*2];\n                for(int i=0;i<poly.pts.size();i++){xy[i*2]=poly.pts.get(i).x;xy[i*2+1]=poly.pts.get(i).y;}\n                candidates=DxfSnapGeometry.poly(xy,true);\n            }else if(entity instanceof SegmentSet){\n                SegmentSet set=(SegmentSet)entity;int segmentCount=Math.min(set.xy.length/4,50000);candidates=new double[segmentCount*6];\n                for(int i=0;i<segmentCount;i++){float x1=set.xy[i*4],y1=set.xy[i*4+1],x2=set.xy[i*4+2],y2=set.xy[i*4+3];int q=i*6;\n                    candidates[q]=x1;candidates[q+1]=y1;candidates[q+2]=x2;candidates[q+3]=y2;candidates[q+4]=(x1+x2)*.5;candidates[q+5]=(y1+y2)*.5;}\n            }\n''')

marker='''    private static Entity bulgedPoly(ArrayList<PointF> points,List<Double> bulges,boolean closed){\n'''
insert='''    private static Entity classicPolyline(DxfBlocks.Record header,List<DxfBlocks.Record> records,List<String> tags)throws IOException{\n        int flags=(int)header.number(70,0);ArrayList<PointF> points=new ArrayList<>();ArrayList<Double> bulges=new ArrayList<>();ArrayList<int[]> faces=new ArrayList<>();\n        for(DxfBlocks.Record vertex:records){\n            int vf=(int)vertex.number(70,0);\n            if((flags&64)!=0&&(vf&128)!=0&&(vf&64)==0){faces.add(new int[]{(int)vertex.number(71,0),(int)vertex.number(72,0),(int)vertex.number(73,0),(int)vertex.number(74,0)});continue;}\n            if(!has(tags,vertex.from,vertex.to,10)||!has(tags,vertex.from,vertex.to,20))continue;\n            points.add(new PointF(f(tags,vertex.from,vertex.to,10),f(tags,vertex.from,vertex.to,20)));bulges.add(vertex.number(42,0));\n        }\n        if((flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(points),faces));\n        if((flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(points),(int)header.number(71,0),(int)header.number(72,0),(flags&1)!=0,(flags&32)!=0));\n        return points.size()<2?null:bulgedPoly(points,bulges,(flags&1)!=0);\n    }\n\n    private static Entity streamPolyline(PendingPoly p){\n        if((p.flags&64)!=0)return segmentSet(DxfPolyMesh.polyface(pointArray(p.points),p.faces));\n        if((p.flags&16)!=0)return segmentSet(DxfPolyMesh.polygonMesh(pointArray(p.points),p.mCount,p.nCount,(p.flags&1)!=0,(p.flags&32)!=0));\n        return p.points.size()<2?null:bulgedPoly(p.points,p.bulges,p.closed);\n    }\n\n    private static Entity segmentSet(double[] packed){return packed!=null&&packed.length>=4?new SegmentSet(packed):null;}\n    private static double[] pointArray(List<PointF> points){double[] xy=new double[points.size()*2];for(int i=0;i<points.size();i++){xy[i*2]=points.get(i).x;xy[i*2+1]=points.get(i).y;}return xy;}\n\n'''+marker
repl(marker,insert)

p.write_text(s)
