from pathlib import Path
p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:220]!r}')
    s=s.replace(old,new,count)

old='''        final float x,y,height,angle,widthFactor,oblique,boxWidth,targetWidth;\n        final String text,fontFamily;final int hAlign,vAlign,attachment;\n        final boolean mtext,backwards,upsideDown,aligned;\n        private Path cached;\n        Label(float x,float y,float h,float angle,String text){\n            this(x,y,h,angle,text,1,0,"sans-serif",0,0,false,1,0,false,false,0,false);\n        }\n        Label(float x,float y,float h,float angle,String text,float widthFactor,float oblique,String fontFamily,\n              int hAlign,int vAlign,boolean mtext,int attachment,float boxWidth,boolean backwards,boolean upsideDown,\n              float targetWidth,boolean aligned){\n            this.x=x;this.y=y;this.height=Math.max(.01f,h);this.angle=angle;this.text=text==null?"":text;\n            this.widthFactor=Math.max(.01f,Math.abs(widthFactor));this.oblique=Float.isFinite(oblique)?oblique:0;\n            this.fontFamily=fontFamily==null||fontFamily.isEmpty()?"sans-serif":fontFamily;this.hAlign=hAlign;this.vAlign=vAlign;\n            this.mtext=mtext;this.attachment=attachment;this.boxWidth=Math.max(0,boxWidth);this.backwards=backwards;this.upsideDown=upsideDown;\n            this.targetWidth=Math.max(0,targetWidth);this.aligned=aligned;\n        }\n'''
new='''        final float x,y,height,angle,widthFactor,oblique,boxWidth,targetWidth,backgroundScale;\n        final String text,fontFamily;final int hAlign,vAlign,attachment,backgroundColor;\n        final boolean mtext,backwards,upsideDown,aligned,backgroundEnabled;\n        private Path cached,cachedBackground;\n        Label(float x,float y,float h,float angle,String text){\n            this(x,y,h,angle,text,1,0,"sans-serif",0,0,false,1,0,false,false,0,false,false,BACKGROUND,1.5f);\n        }\n        Label(float x,float y,float h,float angle,String text,float widthFactor,float oblique,String fontFamily,\n              int hAlign,int vAlign,boolean mtext,int attachment,float boxWidth,boolean backwards,boolean upsideDown,\n              float targetWidth,boolean aligned){\n            this(x,y,h,angle,text,widthFactor,oblique,fontFamily,hAlign,vAlign,mtext,attachment,boxWidth,backwards,upsideDown,targetWidth,aligned,false,BACKGROUND,1.5f);\n        }\n        Label(float x,float y,float h,float angle,String text,float widthFactor,float oblique,String fontFamily,\n              int hAlign,int vAlign,boolean mtext,int attachment,float boxWidth,boolean backwards,boolean upsideDown,\n              float targetWidth,boolean aligned,boolean backgroundEnabled,int backgroundColor,float backgroundScale){\n            this.x=x;this.y=y;this.height=Math.max(.01f,h);this.angle=angle;this.text=text==null?"":text;\n            this.widthFactor=Math.max(.01f,Math.abs(widthFactor));this.oblique=Float.isFinite(oblique)?oblique:0;\n            this.fontFamily=fontFamily==null||fontFamily.isEmpty()?"sans-serif":fontFamily;this.hAlign=hAlign;this.vAlign=vAlign;\n            this.mtext=mtext;this.attachment=attachment;this.boxWidth=Math.max(0,boxWidth);this.backwards=backwards;this.upsideDown=upsideDown;\n            this.targetWidth=Math.max(0,targetWidth);this.aligned=aligned;this.backgroundEnabled=backgroundEnabled;this.backgroundColor=backgroundColor;\n            this.backgroundScale=(float)DxfMTextBackground.boxScale(backgroundScale);\n        }\n'''
repl(old,new)

repl('''            Matrix placement=new Matrix();placement.setTranslate(dx,dy);placement.postRotate(angle);placement.postTranslate(x,y);shape.transform(placement);\n            return shape;\n        }\n        private Path shape(){if(cached==null)cached=buildShape();return new Path(cached);}\n        public void bounds(RectF b){RectF r=new RectF();shape().computeBounds(r,true);if(!r.isEmpty()){add(b,r.left,r.top);add(b,r.right,r.bottom);}}\n        public void draw(Canvas c,Paint p,Matrix m){\n            Path path=shape();path.transform(m);Paint.Style old=p.getStyle();PathEffect effect=p.getPathEffect();\n            p.setPathEffect(null);p.setStyle(Paint.Style.FILL);c.drawPath(path,p);p.setStyle(old);p.setPathEffect(effect);\n        }\n''','''            Matrix placement=new Matrix();placement.setTranslate(dx,dy);placement.postRotate(angle);placement.postTranslate(x,y);\n            if(backgroundEnabled){\n                RectF box=new RectF(r);float pad=(float)DxfMTextBackground.padding(height,backgroundScale);box.inset(-pad,-pad);\n                Path background=new Path();background.addRect(box,Path.Direction.CW);background.transform(placement);cachedBackground=background;\n            }\n            shape.transform(placement);return shape;\n        }\n        private Path shape(){if(cached==null)cached=buildShape();return new Path(cached);}\n        private Path background(){shape();return cachedBackground==null?null:new Path(cachedBackground);}\n        public void bounds(RectF b){\n            RectF r=new RectF();shape().computeBounds(r,true);if(!r.isEmpty()){add(b,r.left,r.top);add(b,r.right,r.bottom);}\n            Path bg=background();if(bg!=null){r.setEmpty();bg.computeBounds(r,true);if(!r.isEmpty()){add(b,r.left,r.top);add(b,r.right,r.bottom);}}\n        }\n        public void draw(Canvas c,Paint p,Matrix m){\n            Path path=shape();path.transform(m);Paint.Style old=p.getStyle();PathEffect effect=p.getPathEffect();int oldColor=p.getColor();\n            p.setPathEffect(null);p.setStyle(Paint.Style.FILL);Path bg=background();if(bg!=null){bg.transform(m);p.setColor(backgroundColor);c.drawPath(bg,p);p.setColor(oldColor);}\n            c.drawPath(path,p);p.setColor(oldColor);p.setStyle(old);p.setPathEffect(effect);\n        }\n''')

repl('''        boolean backwards=false,upsideDown=false;int hAlign=0,vAlign=0,attachment=1;float boxWidth=0,targetWidth=0;\n        float x=f(a,from,to,10),y=f(a,from,to,20),angle=0;boolean aligned=false;\n        if(mtext){\n            attachment=(int)fv(a,from,to,71,1f);boxWidth=Math.max(0,fv(a,from,to,41,0f));\n''','''        boolean backwards=false,upsideDown=false;int hAlign=0,vAlign=0,attachment=1;float boxWidth=0,targetWidth=0;\n        float x=f(a,from,to,10),y=f(a,from,to,20),angle=0;boolean aligned=false;\n        boolean backgroundEnabled=false;int backgroundColor=BACKGROUND;float backgroundScale=1.5f;\n        if(mtext){\n            attachment=(int)fv(a,from,to,71,1f);boxWidth=Math.max(0,fv(a,from,to,41,0f));\n            int backgroundFlags=(int)fv(a,from,to,90,0f);backgroundEnabled=DxfMTextBackground.enabled(backgroundFlags);\n            if(backgroundEnabled){\n                long backgroundTrueColor=-1;String rawColor=str(a,from,to,421,"").trim();\n                if(!rawColor.isEmpty())try{backgroundTrueColor=Long.parseLong(rawColor);}catch(NumberFormatException ignored){}\n                backgroundColor=DxfMTextBackground.color(backgroundFlags,(int)fv(a,from,to,63,0f),backgroundTrueColor,BACKGROUND);\n                backgroundScale=(float)DxfMTextBackground.boxScale(fv(a,from,to,45,1.5f));\n            }\n''')

repl('''        return new Label(x,y,height,angle,plain,width,oblique,style.familyHint(),hAlign,vAlign,mtext,attachment,boxWidth,\n            backwards,upsideDown,targetWidth,aligned);\n''','''        return new Label(x,y,height,angle,plain,width,oblique,style.familyHint(),hAlign,vAlign,mtext,attachment,boxWidth,\n            backwards,upsideDown,targetWidth,aligned,backgroundEnabled,backgroundColor,backgroundScale);\n''')

repl('''            code==330||code==331||code==340||code==370||code==410||code==420||code==440||\n''','''            code==330||code==331||code==340||code==370||code==410||code==420||code==421||code==440||\n''')

p.write_text(s)
