from pathlib import Path
p=Path('app/src/main/java/com/musa/cad/DxfParser.java');s=p.read_text()

def repl(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: raise SystemExit(f'expected {count}, got {n}: {old[:220]!r}')
    s=s.replace(old,new,count)

repl('''    private static final class Marker implements Entity{\n        final float x,y,size;\n        Marker(float x,float y,float size){this.x=x;this.y=y;this.size=size;}\n        public void bounds(RectF b){add(b,x-size,y-size);add(b,x+size,y+size);}\n        public void draw(Canvas c,Paint p,Matrix m){\n            float[] v={x-size,y,x+size,y,x,y-size,x,y+size};m.mapPoints(v);\n            c.drawLine(v[0],v[1],v[2],v[3],p);c.drawLine(v[4],v[5],v[6],v[7],p);\n        }\n    }\n''','''    private static final class Marker implements Entity{\n        final float x,y;final DxfPointStyle.Style style;\n        Marker(float x,float y,DxfPointStyle.Style style){this.x=x;this.y=y;this.style=style==null?new DxfPointStyle.Style(0,0):style;}\n        public void bounds(RectF b){add(b,x,y);}\n        public void draw(Canvas c,Paint p,Matrix m){\n            if(style.hidden())return;float[] center={x,y};m.mapPoints(center);\n            float[] vectors={1,0,0,1};m.mapVectors(vectors);double deviceScale=(Math.hypot(vectors[0],vectors[1])+Math.hypot(vectors[2],vectors[3]))*.5;\n            float h=(float)DxfPointStyle.deviceHalfSize(style,deviceScale,Math.min(c.getWidth(),c.getHeight()));float cx=center[0],cy=center[1];\n            Paint.Style oldStyle=p.getStyle();PathEffect oldEffect=p.getPathEffect();p.setPathEffect(null);int base=style.base();\n            if(base==0){p.setStyle(Paint.Style.FILL);c.drawCircle(cx,cy,Math.max(1f,p.getStrokeWidth()*.75f),p);p.setStyle(Paint.Style.STROKE);}\n            else{p.setStyle(Paint.Style.STROKE);if(base==2){c.drawLine(cx-h,cy,cx+h,cy,p);c.drawLine(cx,cy-h,cx,cy+h,p);}\n                else if(base==3){c.drawLine(cx-h,cy-h,cx+h,cy+h,p);c.drawLine(cx-h,cy+h,cx+h,cy-h,p);}\n                else if(base==4)c.drawLine(cx,cy-h,cx,cy+h,p);\n                else if(base!=1){p.setStyle(Paint.Style.FILL);c.drawCircle(cx,cy,Math.max(1f,p.getStrokeWidth()*.75f),p);p.setStyle(Paint.Style.STROKE);}}\n            if(style.circle()){p.setStyle(Paint.Style.STROKE);c.drawCircle(cx,cy,h,p);}\n            if(style.square()){p.setStyle(Paint.Style.STROKE);c.drawRect(cx-h,cy-h,cx+h,cy+h,p);}\n            p.setStyle(oldStyle);p.setPathEffect(oldEffect);\n        }\n    }\n''')

repl('''    private static int appendBufferedPlacements(List<String> lines,List<DxfBlocks.Placement> placements,\n                                                 DxfLayerTable.Table layerTable,DxfLineTypes.Table lineTypes,DxfTextStyles.Table textStyles,\n                                                 ArrayList<Entity> entities,Set<String> layers,Set<String> visibleLayers,\n                                                 List<LayerEntity> viewportModel)throws IOException{\n''','''    private static int appendBufferedPlacements(List<String> lines,List<DxfBlocks.Placement> placements,\n                                                 DxfLayerTable.Table layerTable,DxfLineTypes.Table lineTypes,DxfTextStyles.Table textStyles,DxfPointStyle.Style pointStyle,\n                                                 ArrayList<Entity> entities,Set<String> layers,Set<String> visibleLayers,\n                                                 List<LayerEntity> viewportModel)throws IOException{\n''')

repl('''                entity=isTextType(item.record.type)?parseTextEntity(item.record.type,lines,item.record.from,item.record.to,textStyles):\n                    parse(item.record.type,lines,item.record.from,item.record.to);\n''','''                entity=isTextType(item.record.type)?parseTextEntity(item.record.type,lines,item.record.from,item.record.to,textStyles):\n                    parse(item.record.type,lines,item.record.from,item.record.to,pointStyle);\n''')

repl('''        DxfTextStyles.Table textStyles=DxfTextStyles.parse(lines);\n        int insUnits=DxfUnits.parse(lines);\n''','''        DxfTextStyles.Table textStyles=DxfTextStyles.parse(lines);\n        DxfPointStyle.Style pointStyle=DxfPointStyle.parse(lines);\n        int insUnits=DxfUnits.parse(lines);\n''')

repl('''            appendBufferedPlacements(lines,modelExpanded.placements,layerTable,lineTypes,textStyles,modelRaw,layers,visibleLayers,null);\n''','''            appendBufferedPlacements(lines,modelExpanded.placements,layerTable,lineTypes,textStyles,pointStyle,modelRaw,layers,visibleLayers,null);\n''')
repl('''        int skipped=expanded.skipped+appendBufferedPlacements(lines,expanded.placements,layerTable,lineTypes,textStyles,\n            entities,layers,visibleLayers,viewportModel);\n''','''        int skipped=expanded.skipped+appendBufferedPlacements(lines,expanded.placements,layerTable,lineTypes,textStyles,pointStyle,\n            entities,layers,visibleLayers,viewportModel);\n''')

repl('''        final DxfTextStyles.Table textStyles=new DxfTextStyles.Table();\n        final Map<String,String> drawOrder=new HashMap<>();\n''','''        final DxfTextStyles.Table textStyles=new DxfTextStyles.Table();\n        DxfPointStyle.Style pointStyle=new DxfPointStyle.Style(0,0);\n        final Map<String,String> drawOrder=new HashMap<>();\n''')

repl('''            if("HEADER".equals(c.section)){\n                c.insUnits=DxfUnits.parseHeaderRecord(r.tags);\n''','''            if("HEADER".equals(c.section)){\n                c.insUnits=DxfUnits.parseHeaderRecord(r.tags);c.pointStyle=DxfPointStyle.parseHeaderRecord(r.tags);\n''')

repl('''        Entity entity=isTextType(type)?parseTextEntity(type,r.tags,0,r.tags.size(),c.textStyles):parse(type,r.tags,0,r.tags.size());\n''','''        Entity entity=isTextType(type)?parseTextEntity(type,r.tags,0,r.tags.size(),c.textStyles):parse(type,r.tags,0,r.tags.size(),c.pointStyle);\n''')

repl('''    private static Entity parse(String type,List<String>a,int from,int to){\n''','''    private static Entity parse(String type,List<String>a,int from,int to,DxfPointStyle.Style pointStyle){\n        if("POINT".equals(type))return new Marker(f(a,from,to,10),f(a,from,to,20),pointStyle);\n        return parse(type,a,from,to);\n    }\n\n    private static Entity parse(String type,List<String>a,int from,int to){\n''')

repl('''        if("POINT".equals(type))return new Marker(f(a,from,to,10),f(a,from,to,20),Math.max(.1f,fv(a,from,to,40,.5f)));\n''','''        if("POINT".equals(type))return new Marker(f(a,from,to,10),f(a,from,to,20),new DxfPointStyle.Style(0,0));\n''')

p.write_text(s)
