package com.musa.cad;

import android.graphics.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Lightweight ASCII DXF renderer for common 2D entities. */
public final class DxfParser {
    private static final int SIZE=2400,MARGIN=80;
    private interface Entity{void bounds(RectF b);void draw(Canvas c,Paint p,Matrix m);}

    private static final class Line implements Entity{
        final float x1,y1,x2,y2;Line(float a,float b,float c,float d){x1=a;y1=b;x2=c;y2=d;}
        public void bounds(RectF b){add(b,x1,y1);add(b,x2,y2);}public void draw(Canvas c,Paint p,Matrix m){float[]v={x1,y1,x2,y2};m.mapPoints(v);c.drawLine(v[0],v[1],v[2],v[3],p);}
    }
    private static final class Poly implements Entity{
        final ArrayList<PointF>pts,snapPts;final boolean closed;Poly(ArrayList<PointF>p,boolean c){this(p,c,p);}Poly(ArrayList<PointF>p,boolean c,ArrayList<PointF>snap){pts=p;closed=c;snapPts=snap==null?p:snap;}
        public void bounds(RectF b){for(PointF p:pts)add(b,p.x,p.y);}public void draw(Canvas c,Paint p,Matrix m){if(pts.size()<2)return;Path q=new Path();float[]v={pts.get(0).x,pts.get(0).y};m.mapPoints(v);q.moveTo(v[0],v[1]);for(int i=1;i<pts.size();i++){v[0]=pts.get(i).x;v[1]=pts.get(i).y;m.mapPoints(v);q.lineTo(v[0],v[1]);}if(closed)q.close();c.drawPath(q,p);}
    }
    private static final class Circle implements Entity{
        final float x,y,r,start,sweep;Circle(float a,float b,float c,float d,float e){x=a;y=b;r=c;start=d;sweep=e;}
        public void bounds(RectF b){add(b,x-r,y-r);add(b,x+r,y+r);}public void draw(Canvas c,Paint p,Matrix m){Path path=new Path();path.addArc(new RectF(x-r,y-r,x+r,y+r),start,sweep);path.transform(m);c.drawPath(path,p);}
    }
    private static final class Marker implements Entity{
        final float x,y,size;Marker(float x,float y,float size){this.x=x;this.y=y;this.size=size;}
        public void bounds(RectF b){add(b,x-size,y-size);add(b,x+size,y+size);}public void draw(Canvas c,Paint p,Matrix m){float[]v={x-size,y,x+size,y,x,y-size,x,y+size};m.mapPoints(v);c.drawLine(v[0],v[1],v[2],v[3],p);c.drawLine(v[4],v[5],v[6],v[7],p);}
    }
    private static final class EllipseCurve implements Entity{
        final float cx,cy,mx,my,ratio,start,end;EllipseCurve(float cx,float cy,float mx,float my,float ratio,float start,float end){this.cx=cx;this.cy=cy;this.mx=mx;this.my=my;this.ratio=Math.abs(ratio);this.start=start;this.end=end;}
        private PointF at(double t){double co=Math.cos(t),si=Math.sin(t);return new PointF((float)(cx+mx*co-my*ratio*si),(float)(cy+my*co+mx*ratio*si));}private double sweep(){double s=end-start;while(s<=0)s+=Math.PI*2;return Math.min(s,Math.PI*2);}
        public void bounds(RectF b){double sw=sweep();for(int i=0;i<=96;i++){PointF q=at(start+sw*i/96d);add(b,q.x,q.y);}}public void draw(Canvas c,Paint p,Matrix m){double sw=sweep();Path path=new Path();for(int i=0;i<=96;i++){PointF q=at(start+sw*i/96d);float[]v={q.x,q.y};m.mapPoints(v);if(i==0)path.moveTo(v[0],v[1]);else path.lineTo(v[0],v[1]);}c.drawPath(path,p);}
    }

    private static final class HatchEntity implements Entity{
        final DxfHatch.Result hatch;HatchEntity(DxfHatch.Result hatch){this.hatch=hatch;}
        public void bounds(RectF b){for(DxfHatch.Loop loop:hatch.loops)for(DxfHatch.Point point:loop.points)add(b,(float)point.x,(float)point.y);}
        private Path path(Matrix m){Path path=new Path();path.setFillType(Path.FillType.EVEN_ODD);for(DxfHatch.Loop loop:hatch.loops){if(loop.points.size()<2)continue;DxfHatch.Point first=loop.points.get(0);path.moveTo((float)first.x,(float)first.y);for(int i=1;i<loop.points.size();i++){DxfHatch.Point point=loop.points.get(i);path.lineTo((float)point.x,(float)point.y);}if(loop.closed)path.close();}path.transform(m);return path;}
        public void draw(Canvas c,Paint p,Matrix m){Path boundary=path(m);RectF bounds=new RectF();boundary.computeBounds(bounds,true);if(bounds.isEmpty())return;p.setPathEffect(null);Paint.Style old=p.getStyle();if(hatch.solid){p.setStyle(Paint.Style.FILL);c.drawPath(boundary,p);p.setStyle(old);return;}if(hatch.patternLines.isEmpty()){p.setStyle(Paint.Style.STROKE);c.drawPath(boundary,p);p.setStyle(old);return;}int save=c.save();c.clipPath(boundary);p.setStyle(Paint.Style.STROKE);double hatchAngle=Math.toRadians(hatch.patternAngleDegrees),co=Math.cos(hatchAngle),si=Math.sin(hatchAngle),scale=hatch.patternScale;float diag=(float)Math.hypot(bounds.width(),bounds.height())+64f;for(DxfHatch.PatternLine line:hatch.patternLines){double bx=(line.baseX*co-line.baseY*si)*scale,by=(line.baseX*si+line.baseY*co)*scale;double ox=(line.offsetX*co-line.offsetY*si)*scale,oy=(line.offsetX*si+line.offsetY*co)*scale;double angle=Math.toRadians(line.angleDegrees+hatch.patternAngleDegrees);float[]base={(float)bx,(float)by};m.mapPoints(base);float[]offset={(float)ox,(float)oy};m.mapVectors(offset);float step=(float)Math.hypot(offset[0],offset[1]);if(step<.5f||!Float.isFinite(step))continue;float[]dir={(float)Math.cos(angle),(float)Math.sin(angle)};m.mapVectors(dir);float length=(float)Math.hypot(dir[0],dir[1]);if(length<1e-6f)continue;dir[0]/=length;dir[1]/=length;DxfLineStyle.Pattern dp=new DxfLineStyle.Pattern("HATCH",line.dashes,false);DxfLineStyle.Dash dash=dp.dash(matrixScale(m),1d,scale,1d);p.setPathEffect(dash==null?null:new DashPathEffect(dash.intervals,dash.phase));int count=Math.min(1600,(int)Math.ceil(diag/step)+6);for(int n=-count;n<=count;n++){float ax=base[0]+offset[0]*n,ay=base[1]+offset[1]*n;c.drawLine(ax-dir[0]*diag*2,ay-dir[1]*diag*2,ax+dir[0]*diag*2,ay+dir[1]*diag*2,p);}}p.setPathEffect(null);c.restoreToCount(save);p.setStyle(old);}
    }

    private static final class ViewportEntity implements Entity{
        final DxfViewport.View viewport;ViewportEntity(DxfViewport.View viewport){this.viewport=viewport;}
        public void bounds(RectF b){add(b,(float)viewport.left(),(float)viewport.bottom());add(b,(float)viewport.right(),(float)viewport.top());}
        public void draw(Canvas c,Paint p,Matrix m){if(viewport.id<=1)return;float[]v={(float)viewport.left(),(float)viewport.bottom(),(float)viewport.right(),(float)viewport.top()};m.mapPoints(v);Paint.Style old=p.getStyle();p.setStyle(Paint.Style.STROKE);c.drawRect(Math.min(v[0],v[2]),Math.min(v[1],v[3]),Math.max(v[0],v[2]),Math.max(v[1],v[3]),p);p.setStyle(old);}
    }

    private static final class Transformed implements Entity{
        final Entity entity;final Matrix matrix;Transformed(Entity entity,DxfBlocks.Transform t)throws IOException{this.entity=entity;float[]v={(float)t.a,(float)t.c,(float)t.x,(float)t.b,(float)t.d,(float)t.y,0,0,1};for(float n:v)if(!Float.isFinite(n))throw new IOException("DXF blok dönüşümü sınır dışında");matrix=new Matrix();matrix.setValues(v);}
        public void bounds(RectF b){RectF local=new RectF(Float.MAX_VALUE,Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE);entity.bounds(local);if(local.left>local.right||local.top>local.bottom)return;matrix.mapRect(local);add(b,local.left,local.top);add(b,local.right,local.bottom);}public void draw(Canvas c,Paint p,Matrix view){Matrix combined=new Matrix();combined.setConcat(view,matrix);entity.draw(c,p,combined);}
    }

    public static final class SourceEntity{
        public final int sourceId;public final SourceRange range;public final String type,layer,lineType,layout;public final int color,lineWeight;public final double lineTypeScale;private final CadEdit prototype;
        SourceEntity(int sourceId,SourceRange range,String type,String layer,String layout,int color,String lineType,double lineTypeScale,int lineWeight,CadEdit prototype){this.sourceId=sourceId;this.range=range;this.type=type;this.layer=layer;this.layout=layout;this.color=color;this.lineType=DxfLineStyle.normalizeName(lineType);this.lineTypeScale=lineTypeScale;this.lineWeight=lineWeight;this.prototype=prototype;}
        public CadEdit prototype(){return prototype.copy();}public float hitDistance(float contentX,float contentY){return prototype.hitDistance(contentX,contentY);}
    }

    public static final class Result{
        public final Bitmap bitmap;public final float[] snapPoints;public final int entityCount,layerCount,skippedCount;public int conversionWarnings;public final Set<String>layerNames,visibleLayers,layoutNames;public final String activeLayout;
        private final List<Entity>document;private final Matrix view;private final RectF contentBounds;private final float worldToContentScale;private final double millimetersPerUnit;private final String drawingUnitName;private final double globalLineTypeScale;private final Map<String,DxfLineStyle.Pattern>lineTypes;private final List<SourceEntity>editableSources;private final Map<Integer,SourceEntity>sourceById;
        Result(Bitmap b,int e,int skipped,float[]points,List<Entity>document,Matrix view,Set<String>all,Set<String>visible,Set<String>layouts,String activeLayout,RectF contentBounds,float worldToContentScale,double millimetersPerUnit,String drawingUnitName,double globalLineTypeScale,Map<String,DxfLineStyle.Pattern>lineTypes){bitmap=b;entityCount=e;skippedCount=skipped;snapPoints=points;this.document=document;this.view=new Matrix(view);this.contentBounds=new RectF(contentBounds);this.worldToContentScale=worldToContentScale;this.millimetersPerUnit=millimetersPerUnit;this.drawingUnitName=drawingUnitName;this.globalLineTypeScale=safeLineTypeScale(globalLineTypeScale);this.lineTypes=Collections.unmodifiableMap(new LinkedHashMap<>(lineTypes));layerNames=Collections.unmodifiableSet(new TreeSet<>(all));visibleLayers=Collections.unmodifiableSet(new TreeSet<>(visible));layoutNames=Collections.unmodifiableSet(new LinkedHashSet<>(layouts));this.activeLayout=activeLayout;layerCount=all.size();ArrayList<SourceEntity>sourceList=new ArrayList<>();LinkedHashMap<Integer,SourceEntity>sourceMap=new LinkedHashMap<>();for(Entity entity:document){LayerEntity layer=(LayerEntity)entity;if(layer.sourceRange==null||layer.sourceEditWorld==null)continue;CadEdit ce=mapEditToContent(layer.sourceEditWorld,this.view);SourceEntity source=new SourceEntity(layer.sourceId,layer.sourceRange,layer.sourceType,layer.layer,layer.layout,layer.color,layer.lineType,layer.lineTypeScale,layer.lineWeight,ce);sourceList.add(source);sourceMap.put(source.sourceId,source);}editableSources=Collections.unmodifiableList(sourceList);sourceById=Collections.unmodifiableMap(sourceMap);}
        public Result withVisibleLayers(Set<String>selected)throws IOException{Set<String>visible=new HashSet<>(selected);visible.retainAll(layerNames);Result r=renderLayout(document,layerNames,visible,layoutNames,activeLayout,skippedCount,millimetersPerUnit,drawingUnitName,globalLineTypeScale,lineTypes);r.conversionWarnings=conversionWarnings;return r;}
        public Result withLayout(String selected)throws IOException{String layout=findLayout(layoutNames,selected);Result r=renderLayout(document,layerNames,visibleLayers,layoutNames,layout,skippedCount,millimetersPerUnit,drawingUnitName,globalLineTypeScale,lineTypes);r.conversionWarnings=conversionWarnings;return r;}
        public int editableSourceCount(){int count=0;for(SourceEntity s:editableSources)if(activeLayout.equals(s.layout)&&visibleLayers.contains(s.layer))count++;return count;}public SourceEntity sourceById(int id){return sourceById.get(id);}public List<SourceEntity>editableSources(){return editableSources;}public boolean isSourceVisible(int id){SourceEntity s=sourceById.get(id);return s!=null&&activeLayout.equals(s.layout)&&visibleLayers.contains(s.layer);}
        public SourceEntity findEditableSource(float x,float y,float tolerance,Set<Integer>hiddenIds){float best=Math.max(0f,tolerance);SourceEntity found=null;Set<Integer>hidden=hiddenIds==null?Collections.emptySet():hiddenIds;for(SourceEntity s:editableSources){if(!activeLayout.equals(s.layout)||hidden.contains(s.sourceId)||!visibleLayers.contains(s.layer))continue;float distance=s.hitDistance(x,y),allowed="TEXT".equals(s.type)?best*1.75f:best;if(distance<=allowed&&(found==null||distance<best)){best=distance;found=s;}}return found;}
        public void drawVector(Canvas canvas,Matrix imageMatrix){drawVector(canvas,imageMatrix,Collections.emptySet());}
        public void drawVector(Canvas canvas,Matrix imageMatrix,Set<Integer>hiddenIds){Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setStyle(Paint.Style.STROKE);Matrix combined=new Matrix();combined.setConcat(imageMatrix,view);drawViewportModels(canvas,paint,combined,document,activeLayout,visibleLayers,false,false,globalLineTypeScale);Set<Integer>hidden=hiddenIds==null?Collections.emptySet():hiddenIds;for(Entity entity:document){LayerEntity layer=(LayerEntity)entity;if(activeLayout.equals(layer.layout)&&visibleLayers.contains(layer.layer)&&!hidden.contains(layer.sourceId))layer.drawStyled(canvas,paint,combined,false,false,globalLineTypeScale);}}
        public void drawVectorForPrint(Canvas canvas,Matrix contentToPage,boolean monochrome){drawVectorForPrint(canvas,contentToPage,monochrome,Collections.emptySet());}
        public void drawVectorForPrint(Canvas canvas,Matrix contentToPage,boolean monochrome,Set<Integer>hiddenIds){Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setStyle(Paint.Style.STROKE);Matrix combined=new Matrix();combined.setConcat(contentToPage,view);drawViewportModels(canvas,paint,combined,document,activeLayout,visibleLayers,true,monochrome,globalLineTypeScale);Set<Integer>hidden=hiddenIds==null?Collections.emptySet():hiddenIds;for(Entity entity:document){LayerEntity layer=(LayerEntity)entity;if(!activeLayout.equals(layer.layout)||!visibleLayers.contains(layer.layer)||hidden.contains(layer.sourceId))continue;layer.drawStyled(canvas,paint,combined,true,monochrome,globalLineTypeScale);}}
        public void drawSourceReplacement(Canvas canvas,Matrix contentToTarget,SourceReplacement r,boolean print,boolean mono){if(canvas==null||contentToTarget==null||r==null||!isSourceVisible(r.sourceId))return;Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setStyle(Paint.Style.STROKE);paint.setColor(mono?Color.BLACK:(print?paperColor(r.color):r.color));paint.setStrokeWidth(print?DxfLineStyle.printStrokePoints(r.lineWeight):DxfLineStyle.screenStroke(r.lineWeight));DxfLineStyle.Pattern pattern=lineTypes.get(DxfLineStyle.normalizeName(r.lineType));if(pattern==null)pattern=lineTypes.get(DxfLineStyle.CONTINUOUS);double pixels=matrixScale(contentToTarget)*worldToContentScale;DxfLineStyle.Dash dash=pattern==null?null:pattern.dash(pixels,globalLineTypeScale,r.lineTypeScale,1d);paint.setPathEffect(dash==null?null:new DashPathEffect(dash.intervals,dash.phase));drawContentEdit(canvas,paint,contentToTarget,r.edit);paint.setPathEffect(null);}
        public Matrix printMatrix(RectF target,int denominator){Matrix matrix=new Matrix();if(target==null||target.width()<=0||target.height()<=0)return matrix;double points=CadPrintMath.pointsPerDrawingUnit(millimetersPerUnit,denominator);if(denominator>0&&Double.isFinite(points)&&worldToContentScale>0){float scale=(float)(points/worldToContentScale);matrix.setScale(scale,scale);RectF mapped=new RectF(contentBounds);matrix.mapRect(mapped);matrix.postTranslate(target.centerX()-mapped.centerX(),target.centerY()-mapped.centerY());}else matrix.setRectToRect(contentBounds,target,Matrix.ScaleToFit.CENTER);return matrix;}
        public boolean hasPhysicalUnits(){return Double.isFinite(millimetersPerUnit)&&millimetersPerUnit>0;}public String drawingUnitName(){return drawingUnitName;}public float drawingAspectRatio(){return contentBounds.height()>0?contentBounds.width()/contentBounds.height():1f;}public int contentWidth(){return SIZE;}public int contentHeight(){return SIZE;}
    }

    private static final class LayerEntity implements Entity{
        final Entity entity;final String layer,layout;final int color;final String lineType;final DxfLineStyle.Pattern linePattern;final double lineTypeScale,blockScale;final int lineWeight,sourceId;final SourceRange sourceRange;final String sourceType;final CadEdit sourceEditWorld;
        LayerEntity(Entity e,String layer,String layout,int color,String lineType,DxfLineStyle.Pattern pattern,double scale,int weight,double blockScale,int sourceId,SourceRange range,String type,CadEdit edit){entity=e;this.layer=layer;this.layout=layout;this.color=color;this.lineType=DxfLineStyle.normalizeName(lineType);linePattern=pattern;lineTypeScale=safeLineTypeScale(scale);lineWeight=weight;this.blockScale=blockScale;this.sourceId=sourceId;sourceRange=range;sourceType=type;sourceEditWorld=edit;}
        public void bounds(RectF b){entity.bounds(b);}public void draw(Canvas c,Paint p,Matrix m){drawStyled(c,p,m,false,false,1d);}void drawStyled(Canvas c,Paint p,Matrix m,boolean print,boolean mono,double global){p.setColor(mono?Color.BLACK:(print?paperColor(color):color));p.setStrokeWidth(print?DxfLineStyle.printStrokePoints(lineWeight):DxfLineStyle.screenStroke(lineWeight));DxfLineStyle.Dash dash=linePattern==null?null:linePattern.dash(matrixScale(m),global,lineTypeScale,blockScale);p.setPathEffect(dash==null?null:new DashPathEffect(dash.intervals,dash.phase));entity.draw(c,p,m);p.setPathEffect(null);}
    }

    private static int paperColor(int color){int r=Color.red(color),g=Color.green(color),b=Color.blue(color);return r>=245&&g>=245&&b>=245?Color.BLACK:Color.rgb(r,g,b);}
    private static final class Label implements Entity{
        final float x,y,height,angle,widthFactor,oblique,offsetX,offsetY;final int generationFlags,mtextAttachment;final String text;final String[]rows;final DxfTextStyle.Style style;
        Label(float x,float y,float h,float angle,String text,DxfTextStyle.Style style,float width,float oblique,int flags,float x2,float y2,boolean hasSecond,int horizontal,int vertical,int attachment){
            this.text=text;this.style=style==null?DxfTextStyle.defaultStyle():style;generationFlags=flags;mtextAttachment=attachment;rows=text.split("\n",-1);float baseWidth=Math.max(.01f,width),baseHeight=Math.max(.01f,h);Paint measure=new Paint(Paint.ANTI_ALIAS_FLAG);measure.setTypeface(typeface(this.style));measure.setTextSize(baseHeight);measure.setTextScaleX(baseWidth);measure.setTextSkewX((float)-Math.tan(Math.toRadians(oblique)));float measured=.0001f;for(String row:rows)measured=Math.max(measured,measure.measureText(row));DxfTextAlign.Result aligned=DxfTextAlign.resolve(x,y,x2,y2,hasSecond,horizontal,vertical,angle,measured,baseHeight);this.x=aligned.x;this.y=aligned.y;this.angle=aligned.angleDegrees;height=baseHeight*aligned.heightScale;widthFactor=Math.max(.01f,baseWidth*aligned.widthScale/aligned.heightScale);this.oblique=oblique;offsetX=aligned.localOffsetX;offsetY=aligned.localOffsetY;
        }
        private static Typeface typeface(DxfTextStyle.Style style){return style.usesShx()?Typeface.MONOSPACE:Typeface.create(style.familyHint(),Typeface.NORMAL);}private Typeface typeface(){return typeface(style);}
        private float[] baseline(){float sx=(generationFlags&2)!=0?-1f:1f,sy=(generationFlags&4)!=0?1f:-1f,lx=offsetX*sx,ly=offsetY*sy;double r=Math.toRadians(angle),co=Math.cos(r),si=Math.sin(r);return new float[]{(float)(x+lx*co-ly*si),(float)(y+lx*si+ly*co)};}
        private Path shape(){Paint tp=new Paint(Paint.ANTI_ALIAS_FLAG);tp.setTypeface(typeface());tp.setTextSize(height);tp.setTextScaleX(widthFactor);tp.setTextSkewX((float)-Math.tan(Math.toRadians(oblique)));Path shape=new Path();for(int i=0;i<rows.length;i++){Path line=new Path();tp.getTextPath(rows[i],0,rows[i].length(),offsetX,offsetY+i*height*1.3f,line);shape.addPath(line);}float sx=(generationFlags&2)!=0?-1f:1f,sy=(generationFlags&4)!=0?1f:-1f;Matrix mirror=new Matrix();mirror.setScale(sx,sy);shape.transform(mirror);if(mtextAttachment>=1&&mtextAttachment<=9){RectF bounds=new RectF();shape.computeBounds(bounds,true);if(!bounds.isEmpty()){float[]shift=DxfTextAlign.mtextOffset(mtextAttachment,bounds.left,bounds.top,bounds.right,bounds.bottom);Matrix anchor=new Matrix();anchor.setTranslate(shift[0],shift[1]);shape.transform(anchor);}}Matrix placement=new Matrix();placement.setRotate(angle);placement.postTranslate(x,y);shape.transform(placement);return shape;}public void bounds(RectF b){RectF r=new RectF();shape().computeBounds(r,true);add(b,r.left,r.top);add(b,r.right,r.bottom);}public void draw(Canvas c,Paint p,Matrix m){Path path=shape();path.transform(m);p.setStyle(Paint.Style.FILL);c.drawPath(path,p);p.setStyle(Paint.Style.STROKE);}
    }

    private static String str(List<String>a,int from,int to,int code,String fallback){for(int i=from;i+1<to;i+=2)if(intOf(a.get(i))==code)return a.get(i+1);return fallback;}

    public static Result render(File file)throws IOException{
        List<String>lines=readLines(file);Map<String,DxfTextStyle.Style>styles=DxfTextStyle.parse(lines);int units=headerInt(lines,"$INSUNITS",70,0);double mm=CadPrintMath.millimetersPerUnit(units);String unitName=CadPrintMath.unitName(units);int defaultWeight=DxfLineStyle.normalizeWeight(headerInt(lines,"$LWDEFAULT",370,DxfLineStyle.DEFAULT_LINEWEIGHT),DxfLineStyle.DEFAULT_LINEWEIGHT);double globalScale=safeLineTypeScale(headerDouble(lines,"$LTSCALE",40,1d));DxfBlocks.Result expanded=DxfBlocks.expand(lines,defaultWeight);ArrayList<Entity>entities=new ArrayList<>();Set<String>layers=new HashSet<>();LinkedHashSet<String>layouts=new LinkedHashSet<>();int skipped=expanded.skipped;List<DxfBlocks.Placement>placements=expanded.placements;DxfLineStyle.Pattern continuous=expanded.lineTypes.get(DxfLineStyle.CONTINUOUS);
        for(int index=0;index<placements.size();index++){FileTransfer.checkCancelled();DxfBlocks.Placement item=placements.get(index);Entity entity;if("POLYLINE".equals(item.record.type)){ArrayList<DxfBulge.Vertex>vertices=new ArrayList<>();int j=index+1;while(j<placements.size()&&"VERTEX".equals(placements.get(j).record.type)){DxfBlocks.Record vertex=placements.get(j).record;vertices.add(new DxfBulge.Vertex(f(lines,vertex.from,vertex.to,10),f(lines,vertex.from,vertex.to,20),fv(lines,vertex.from,vertex.to,42,0f)));j++;}boolean closed=(((int)item.record.number(70,0))&1)!=0;entity=bulgePoly(vertices,closed);if(entity==null){skipped++;continue;}index=j-1;}else if("VERTEX".equals(item.record.type)){skipped++;continue;}else{entity=parse(item.record.type,lines,item.record.from,item.record.to,styles);if(entity==null){skipped++;continue;}}CadEdit sourceEdit=item.directRoot?sourceEdit(entity,item.record.type):null;SourceRange range=sourceEdit==null?null:new SourceRange(item.record.from,Math.max(0,item.record.from-2),item.record.to);int sourceId=range==null?-1:range.sourceId;DxfLineStyle.Pattern pattern=expanded.lineTypes.get(item.lineType);if(pattern==null)pattern=continuous;entities.add(new LayerEntity(new Transformed(entity,item.transform),item.layer,item.layout,item.color,item.lineType,pattern,item.lineTypeScale,item.lineWeight,item.blockScale,sourceId,range,item.record.type,sourceEdit));layers.add(item.layer);layouts.add(item.layout);}
        if(entities.isEmpty())return null;String initial=findLayout(layouts,layouts.contains(DxfBlocks.MODEL_LAYOUT)?DxfBlocks.MODEL_LAYOUT:layouts.iterator().next());return renderLayout(entities,layers,layers,layouts,initial,skipped,mm,unitName,globalScale,expanded.lineTypes);
    }

    private static Result renderLayout(List<Entity>document,Set<String>all,Set<String>visible,Set<String>layouts,String requested,int skipped,double mm,String unitName,double global,Map<String,DxfLineStyle.Pattern>lineTypes)throws IOException{
        String active=findLayout(layouts,requested);ArrayList<Entity>layoutEntities=new ArrayList<>();for(Entity entity:document){LayerEntity layer=(LayerEntity)entity;if(active.equals(layer.layout))layoutEntities.add(entity);}if(layoutEntities.isEmpty())throw new IOException("Seçilen layout içinde desteklenen geometri bulunamadı");RectF b=new RectF(Float.MAX_VALUE,Float.MAX_VALUE,-Float.MAX_VALUE,-Float.MAX_VALUE);for(Entity e:layoutEntities){FileTransfer.checkCancelled();e.bounds(b);}if(!Float.isFinite(b.left)||!Float.isFinite(b.top)||b.right<b.left||b.bottom<b.top)throw new IOException("Layout sınırları hesaplanamadı");if(b.width()==0){b.left-=.5f;b.right+=.5f;}if(b.height()==0){b.top-=.5f;b.bottom+=.5f;}float s=Math.min((SIZE-2f*MARGIN)/b.width(),(SIZE-2f*MARGIN)/b.height());Matrix view=new Matrix();view.postTranslate(-b.left,-b.bottom);view.postScale(s,-s);view.postTranslate(MARGIN+(SIZE-2*MARGIN-b.width()*s)/2f,MARGIN+(SIZE-2*MARGIN-b.height()*s)/2f);RectF contentBounds=new RectF(b);view.mapRect(contentBounds);ArrayList<Entity>shown=new ArrayList<>();for(Entity e:layoutEntities){LayerEntity layer=(LayerEntity)e;if(visible.contains(layer.layer))shown.add(e);}Bitmap bitmap=Bitmap.createBitmap(SIZE,SIZE,Bitmap.Config.ARGB_8888);
        try{Canvas canvas=new Canvas(bitmap);canvas.drawColor(Color.rgb(18,24,30));Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);paint.setStyle(Paint.Style.STROKE);drawViewportModels(canvas,paint,view,document,active,visible,false,false,global);for(Entity e:shown){FileTransfer.checkCancelled();((LayerEntity)e).drawStyled(canvas,paint,view,false,false,global);}FileTransfer.checkCancelled();return new Result(bitmap,shown.size(),skipped,snapPoints(shown,view),document,view,all,visible,layouts,active,contentBounds,s,mm,unitName,global,lineTypes);}catch(IOException|RuntimeException|OutOfMemoryError e){bitmap.recycle();throw e;}
    }

    private static void drawViewportModels(Canvas canvas,Paint paint,Matrix paperMatrix,List<Entity>document,String activeLayout,Set<String>visible,boolean print,boolean mono,double global)throws IOException{
        if(DxfBlocks.MODEL_LAYOUT.equalsIgnoreCase(activeLayout))return;ArrayList<LayerEntity>model=new ArrayList<>();ArrayList<ViewportEntity>viewports=new ArrayList<>();for(Entity e:document){LayerEntity layer=(LayerEntity)e;if(DxfBlocks.MODEL_LAYOUT.equalsIgnoreCase(layer.layout)&&visible.contains(layer.layer))model.add(layer);if(activeLayout.equals(layer.layout)){ViewportEntity vp=viewportOf(layer);if(vp!=null&&vp.viewport.active2d())viewports.add(vp);}}if(model.isEmpty()||viewports.isEmpty())return;for(ViewportEntity viewportEntity:viewports){FileTransfer.checkCancelled();DxfViewport.View vp=viewportEntity.viewport;float scale=(float)vp.scale();if(!Float.isFinite(scale)||scale<=0f)continue;Matrix modelToPaper=new Matrix();modelToPaper.postTranslate((float)-vp.modelCenterX(),(float)-vp.modelCenterY());modelToPaper.postRotate((float)-vp.twistDegrees);modelToPaper.postScale(scale,scale);modelToPaper.postTranslate((float)vp.paperCenterX,(float)vp.paperCenterY);Matrix combined=new Matrix();combined.setConcat(paperMatrix,modelToPaper);RectF clip=new RectF((float)vp.left(),(float)vp.bottom(),(float)vp.right(),(float)vp.top());paperMatrix.mapRect(clip);int save=canvas.save();canvas.clipRect(clip);for(LayerEntity layer:model)layer.drawStyled(canvas,paint,combined,print,mono,global);canvas.restoreToCount(save);}}
    private static ViewportEntity viewportOf(LayerEntity layer){Entity e=layer.entity;if(e instanceof Transformed)e=((Transformed)e).entity;return e instanceof ViewportEntity?(ViewportEntity)e:null;}private static String findLayout(Set<String>layouts,String requested){if(layouts==null||layouts.isEmpty())return DxfBlocks.MODEL_LAYOUT;if(requested!=null)for(String l:layouts)if(l.equalsIgnoreCase(requested.trim()))return l;if(layouts.contains(DxfBlocks.MODEL_LAYOUT))return DxfBlocks.MODEL_LAYOUT;return layouts.iterator().next();}

    private static void drawContentEdit(Canvas canvas,Paint paint,Matrix matrix,CadEdit edit){
        if(edit==null)return;float[]v=edit.xy.clone();matrix.mapPoints(v);
        switch(edit.type){
            case LINE:canvas.drawLine(v[0],v[1],v[2],v[3],paint);break;
            case RECTANGLE:canvas.drawRect(Math.min(v[0],v[2]),Math.min(v[1],v[3]),Math.max(v[0],v[2]),Math.max(v[1],v[3]),paint);break;
            case CIRCLE:canvas.drawCircle(v[0],v[1],(float)Math.hypot(v[2]-v[0],v[3]-v[1]),paint);break;
            case POLYLINE:if(v.length>=4){Path path=new Path();path.moveTo(v[0],v[1]);for(int i=2;i+1<v.length;i+=2)path.lineTo(v[i],v[i+1]);if(edit.closed)path.close();canvas.drawPath(path,paint);}break;
            case TEXT:{Paint.Style oldStyle=paint.getStyle();Typeface oldFace=paint.getTypeface();float oldSize=paint.getTextSize(),oldScale=paint.getTextScaleX(),oldSkew=paint.getTextSkewX();paint.setStyle(Paint.Style.FILL);if(edit.hasTextStyle()){paint.setTypeface(edit.textShx?Typeface.MONOSPACE:Typeface.create(edit.textFamilyHint,Typeface.NORMAL));paint.setTextSize(Math.max(1f,edit.textHeight*matrixScale(matrix)));paint.setTextScaleX(edit.textWidthFactor);paint.setTextSkewX((float)-Math.tan(Math.toRadians(edit.textOblique)));}else paint.setTextSize(Math.max(8f,30f*matrixScale(matrix)));int save=canvas.save();canvas.rotate(edit.rotationDegrees,v[0],v[1]);if(edit.hasTextStyle())canvas.scale((edit.textGenerationFlags&2)!=0?-1f:1f,(edit.textGenerationFlags&4)!=0?-1f:1f,v[0],v[1]);canvas.drawText(edit.text==null?"":edit.text,v[0],v[1],paint);canvas.restoreToCount(save);paint.setTypeface(oldFace);paint.setTextSize(oldSize);paint.setTextScaleX(oldScale);paint.setTextSkewX(oldSkew);paint.setStyle(oldStyle);break;}
        }
    }

    private static CadEdit sourceEdit(Entity entity,String type){
        if(entity instanceof Line&&"LINE".equals(type)){Line l=(Line)entity;return CadEdit.line(l.x1,l.y1,l.x2,l.y2);}
        if(entity instanceof Poly&&"LWPOLYLINE".equals(type)){Poly p=(Poly)entity;float[]xy=new float[p.snapPts.size()*2];for(int i=0;i<p.snapPts.size();i++){xy[i*2]=p.snapPts.get(i).x;xy[i*2+1]=p.snapPts.get(i).y;}return CadEdit.polyline(xy,p.closed);}
        if(entity instanceof Circle&&"CIRCLE".equals(type)){Circle c=(Circle)entity;return CadEdit.circle(c.x,c.y,c.x+c.r,c.y);}
        if(entity instanceof Label&&"TEXT".equals(type)){Label l=(Label)entity;float[]base=l.baseline();return CadEdit.styledText(base[0],base[1],l.text,l.angle,l.style.name,l.style.familyHint(),l.style.usesShx(),l.height,l.widthFactor,l.oblique,l.generationFlags);}
        return null;
    }
    private static CadEdit mapEditToContent(CadEdit world,Matrix view){float[]xy=world.xy.clone();view.mapPoints(xy);switch(world.type){case LINE:return CadEdit.line(xy[0],xy[1],xy[2],xy[3]);case CIRCLE:return CadEdit.circle(xy[0],xy[1],xy[2],xy[3]);case POLYLINE:return CadEdit.polyline(xy,world.closed);case TEXT:{float h=world.hasTextStyle()?world.textHeight*matrixScale(view):0f;return CadEdit.styledText(xy[0],xy[1],world.text,-world.rotationDegrees,world.textStyleName,world.textFamilyHint,world.textShx,h,world.textWidthFactor,world.textOblique,world.textGenerationFlags);}case RECTANGLE:return CadEdit.rectangle(xy[0],xy[1],xy[2],xy[3]);default:return world.copy();}}
    private static float[]snapPoints(List<Entity>entities,Matrix matrix){ArrayList<PointF>points=new ArrayList<>();for(Entity wrapped:entities){Entity entity=((LayerEntity)wrapped).entity;Matrix transform=new Matrix();if(entity instanceof Transformed){transform=((Transformed)entity).matrix;entity=((Transformed)entity).entity;}ArrayList<PointF>local=new ArrayList<>();if(entity instanceof Line){Line l=(Line)entity;local.add(new PointF(l.x1,l.y1));local.add(new PointF(l.x2,l.y2));}else if(entity instanceof Poly)local.addAll(((Poly)entity).snapPts);for(PointF point:local){float[]xy={point.x,point.y};transform.mapPoints(xy);points.add(new PointF(xy[0],xy[1]));}}float[]result=new float[points.size()*2];for(int i=0;i<points.size();i++){result[i*2]=points.get(i).x;result[i*2+1]=points.get(i).y;}matrix.mapPoints(result);return result;}

    private static Entity parse(String type,List<String>a,int from,int to,Map<String,DxfTextStyle.Style>styles){
        if("TEXT".equals(type)||"MTEXT".equals(type)||"ATTRIB".equals(type)||"ATTDEF".equals(type)){StringBuilder text=new StringBuilder();for(int i=from;i+1<to;i+=2){int code=intOf(a.get(i));if(code==1||("MTEXT".equals(type)&&code==3))text.append(a.get(i+1));}String plain=DxfText.plain(text.toString());if(plain.trim().isEmpty())return null;DxfTextStyle.Style style=DxfTextStyle.resolve(styles,str(a,from,to,7,DxfTextStyle.STANDARD));float angle=f(a,from,to,50);boolean mtext="MTEXT".equals(type);if(mtext){angle=(float)Math.toDegrees(angle);if(!str(a,from,to,11,"").isEmpty())angle=(float)Math.toDegrees(Math.atan2(f(a,from,to,21),f(a,from,to,11)));}float raw=Math.max(.01f,fv(a,from,to,40,1f)),height=style.textHeight(raw);float entityWidth=mtext?1f:fv(a,from,to,41,1f),width=style.width(entityWidth);float entityOblique=mtext?0f:fv(a,from,to,51,0f),oblique=style.oblique(entityOblique);int generation=style.generation(mtext?0:(int)fv(a,from,to,71,0f));float x=f(a,from,to,10),y=f(a,from,to,20);boolean alignable=!mtext,hasSecond=alignable&&has(a,from,to,11)&&has(a,from,to,21);float x2=hasSecond?f(a,from,to,11):x,y2=hasSecond?f(a,from,to,21):y;int horizontal=alignable?(int)fv(a,from,to,72,0f):0;int vertical="TEXT".equals(type)?(int)fv(a,from,to,73,0f):("ATTRIB".equals(type)||"ATTDEF".equals(type))?(int)fv(a,from,to,74,0f):0;int attachment=mtext?(int)fv(a,from,to,71,1f):0;return new Label(x,y,height,angle,plain,style,width,oblique,generation,x2,y2,hasSecond,horizontal,vertical,attachment);}
        if("LINE".equals(type))return new Line(f(a,from,to,10),f(a,from,to,20),f(a,from,to,11),f(a,from,to,21));if("POINT".equals(type))return new Marker(f(a,from,to,10),f(a,from,to,20),Math.max(.1f,fv(a,from,to,40,.5f)));if("CIRCLE".equals(type))return new Circle(f(a,from,to,10),f(a,from,to,20),Math.abs(f(a,from,to,40)),0,360);if("ARC".equals(type)){float start=f(a,from,to,50),end=f(a,from,to,51),sweep=end-start;if(sweep<0)sweep+=360;return new Circle(f(a,from,to,10),f(a,from,to,20),Math.abs(f(a,from,to,40)),start,sweep);}if("ELLIPSE".equals(type)){float mx=f(a,from,to,11),my=f(a,from,to,21);if(Math.hypot(mx,my)<1e-6)return null;return new EllipseCurve(f(a,from,to,10),f(a,from,to,20),mx,my,fv(a,from,to,40,1f),fv(a,from,to,41,0f),fv(a,from,to,42,(float)(Math.PI*2)));}if("LWPOLYLINE".equals(type)){boolean closed=(((int)f(a,from,to,70))&1)!=0;return bulgePoly(lwVertices(a,from,to),closed);}if("SPLINE".equals(type)){try{return splinePoly(DxfSpline.parse(a,from,to));}catch(IOException ignored){return null;}}if("LEADER".equals(type)){ArrayList<PointF>p=repeatedPoints(a,from,to,10,20);return p.size()<2?null:new Poly(p,false);}if("HATCH".equals(type)){try{DxfHatch.Result h=DxfHatch.parse(a,from,to);return h.loops.isEmpty()?null:new HatchEntity(h);}catch(IOException ignored){return null;}}if("VIEWPORT".equals(type)){DxfViewport.View vp=DxfViewport.parse(a,from,to);return vp.id>1&&vp.paperWidth>0&&vp.paperHeight>0?new ViewportEntity(vp):null;}if("SOLID".equals(type)||"TRACE".equals(type)||"3DFACE".equals(type)){ArrayList<PointF>p=numberedPoints(a,from,to,10,20,4);return p.size()<2?null:new Poly(p,true);}if("DIMENSION".equals(type)){ArrayList<PointF>p=new ArrayList<>();addPointIfPresent(p,a,from,to,13,23);addPointIfPresent(p,a,from,to,14,24);addPointIfPresent(p,a,from,to,10,20);return p.size()<2?null:new Poly(p,false);}return null;
    }

    private static Poly splinePoly(DxfSpline.Result spline){if(spline==null||spline.points.size()<2)return null;ArrayList<PointF>draw=new ArrayList<>(spline.points.size());for(DxfSpline.Point p:spline.points)draw.add(new PointF((float)p.x,(float)p.y));List<DxfSpline.Point>source=!spline.fitPoints.isEmpty()?spline.fitPoints:spline.controlPoints;ArrayList<PointF>snap=new ArrayList<>(source.size());for(DxfSpline.Point p:source)snap.add(new PointF((float)p.x,(float)p.y));if(snap.isEmpty())snap.addAll(draw);return new Poly(draw,spline.closed(),snap);}
    private static ArrayList<DxfBulge.Vertex>lwVertices(List<String>a,int from,int to){ArrayList<DxfBulge.Vertex>out=new ArrayList<>();Double x=null,y=null,bulge=0d;for(int i=from;i+1<to;i+=2){int code=intOf(a.get(i));if(code==10){if(x!=null&&y!=null)out.add(new DxfBulge.Vertex(x,y,bulge));x=(double)floatOf(a.get(i+1));y=null;bulge=0d;}else if(code==20&&x!=null)y=(double)floatOf(a.get(i+1));else if(code==42&&x!=null)bulge=(double)floatOf(a.get(i+1));}if(x!=null&&y!=null)out.add(new DxfBulge.Vertex(x,y,bulge));return out;}
    private static Poly bulgePoly(List<DxfBulge.Vertex>vertices,boolean closed){if(vertices==null||vertices.size()<2)return null;List<DxfBulge.Point>expanded=DxfBulge.expand(vertices,closed);ArrayList<PointF>draw=new ArrayList<>(expanded.size()),snap=new ArrayList<>(vertices.size());for(DxfBulge.Point p:expanded)draw.add(new PointF((float)p.x,(float)p.y));for(DxfBulge.Vertex v:vertices)snap.add(new PointF((float)v.x,(float)v.y));return draw.size()<2?null:new Poly(draw,closed,snap);}
    private static ArrayList<PointF>repeatedPoints(List<String>a,int from,int to,int xCode,int yCode){ArrayList<PointF>p=new ArrayList<>();Float x=null;for(int i=from;i+1<to;i+=2){int code=intOf(a.get(i));if(code==xCode)x=floatOf(a.get(i+1));else if(code==yCode&&x!=null){p.add(new PointF(x,floatOf(a.get(i+1))));x=null;}}return p;}private static ArrayList<PointF>numberedPoints(List<String>a,int from,int to,int xb,int yb,int count){ArrayList<PointF>p=new ArrayList<>();for(int i=0;i<count;i++)addPointIfPresent(p,a,from,to,xb+i,yb+i);return p;}private static void addPointIfPresent(ArrayList<PointF>p,List<String>a,int from,int to,int xc,int yc){if(has(a,from,to,xc)&&has(a,from,to,yc))p.add(new PointF(f(a,from,to,xc),f(a,from,to,yc)));}private static boolean has(List<String>a,int from,int to,int wanted){for(int i=from;i+1<to;i+=2)if(intOf(a.get(i))==wanted)return true;return false;}
    private static int headerInt(List<String>a,String variable,int wantedCode,int fallback){for(int i=0;i+1<a.size();i+=2){if(intOf(a.get(i))!=9||!variable.equals(a.get(i+1).trim()))continue;for(int j=i+2;j+1<a.size();j+=2){int code=intOf(a.get(j));if(code==9||code==0)break;if(code==wantedCode)return intOf(a.get(j+1));}}return fallback;}private static double headerDouble(List<String>a,String variable,int wantedCode,double fallback){for(int i=0;i+1<a.size();i+=2){if(intOf(a.get(i))!=9||!variable.equals(a.get(i+1).trim()))continue;for(int j=i+2;j+1<a.size();j+=2){int code=intOf(a.get(j));if(code==9||code==0)break;if(code==wantedCode){try{double v=Double.parseDouble(a.get(j+1).trim());return Double.isFinite(v)?v:fallback;}catch(Exception ignored){return fallback;}}}}return fallback;}private static double safeLineTypeScale(double value){return Double.isFinite(value)&&value>0?value:1d;}private static float matrixScale(Matrix matrix){float[]v=new float[9];matrix.getValues(v);double sx=Math.hypot(v[Matrix.MSCALE_X],v[Matrix.MSKEW_Y]),sy=Math.hypot(v[Matrix.MSKEW_X],v[Matrix.MSCALE_Y]),s=(sx+sy)/2d;return Double.isFinite(s)&&s>0?(float)s:1f;}
    private static List<String>readLines(File f)throws IOException{ArrayList<String>r=new ArrayList<>();try(BufferedReader b=new BufferedReader(new InputStreamReader(new FileInputStream(f),charset(f)))){String s;while((s=b.readLine())!=null){FileTransfer.checkCancelled();if(r.size()>=600000)throw new IOException("DXF etiket sınırı aşıldı");r.add(s);}}return r;}private static int intOf(String s){try{return Integer.parseInt(s.trim());}catch(Exception e){return-1;}}private static float floatOf(String s){try{return Float.parseFloat(s.trim());}catch(Exception e){return 0;}}private static float f(List<String>a,int from,int to,int wanted){for(int i=from;i+1<to;i+=2)if(intOf(a.get(i))==wanted)return floatOf(a.get(i+1));return 0;}private static float fv(List<String>a,int from,int to,int wanted,float fallback){for(int i=from;i+1<to;i+=2)if(intOf(a.get(i))==wanted)return floatOf(a.get(i+1));return fallback;}private static void add(RectF b,float x,float y){b.left=Math.min(b.left,x);b.top=Math.min(b.top,y);b.right=Math.max(b.right,x);b.bottom=Math.max(b.bottom,y);}
    private static java.nio.charset.Charset charset(File file)throws IOException{String header;try(InputStream in=new FileInputStream(file)){byte[]bytes=new byte[65536];int n=in.read(bytes);header=new String(bytes,0,Math.max(0,n),StandardCharsets.ISO_8859_1);}java.util.regex.Matcher v=java.util.regex.Pattern.compile("AC10([0-9]{2})").matcher(header);if(v.find()&&Integer.parseInt(v.group(1))>=21)return StandardCharsets.UTF_8;java.util.regex.Matcher cp=java.util.regex.Pattern.compile("ANSI_([0-9]+)").matcher(header);try{if(cp.find())return java.nio.charset.Charset.forName("windows-"+cp.group(1));}catch(Exception ignored){}return java.nio.charset.Charset.forName("windows-1252");}
    private DxfParser(){}
}
