package com.musa.cad;

import java.text.Normalizer;
import java.util.Locale;

/**
 * Presentation policy for cloud AI answers. Model identity is server metadata,
 * not a free-form claim generated by the model. Cost/takeoff output is opt-in.
 */
public final class MusaAiReplyPolicy {
    private MusaAiReplyPolicy() {}

    public static boolean asksModelIdentity(String prompt) {
        String q=normalize(prompt);
        if(q.isEmpty())return false;
        // Do not hijack engineering questions about the capabilities of a model.
        if(contains(q,"kapasite","performans","karsilastir","kiyas","ozellik",
                "neden","nasil calisir","mimari model","3d model"))return false;
        boolean identity=contains(q,"model","hangi yapay zeka","hangi ai","ai motoru");
        boolean aiContext=contains(q,"yapay zeka","gandalf","qwen","gemini","claude",
                "chatgpt","baglanti testi","hangi model","kullanilan model","ai modeli")
                || (" "+q+" ").contains(" ai ");
        boolean question=contains(q,"hangi","soyle","kullanilan","kullaniyor",
                "nedir","ismi","adi","testi","modelsin");
        return identity&&aiContext&&question;
    }

    public static boolean wantsTakeoff(String prompt) {
        String q=normalize(prompt);
        return contains(q,"metraj","kesif","poz kitabi","poz no","poz tarif",
                "birim fiyat","malzeme list","maliyet","fiyatlandir",
                "quantity takeoff","bill of quantities","boq");
    }

    /** Use only trusted provider/model fields returned by MusaCAD's own gateway. */
    public static String verifiedModelAnswer(String provider,String model) {
        if(provider==null||provider.trim().isEmpty()||
                model==null||model.trim().isEmpty())
            return "Yapay zekâ yanıt verdi; ancak sunucunun doğrulanmış model bilgisi bulunmuyor.";
        String name;
        switch(provider.trim().toLowerCase(Locale.ROOT)) {
            case "cloudflare":name="Cloudflare Workers AI";break;
            case "gemini":name="Google Gemini";break;
            case "openai":name="OpenAI";break;
            case "selfhosted":name="Özel yapay zekâ sunucusu";break;
            default:name="Yapılandırılmış yapay zekâ sunucusu";break;
        }
        return "Bağlantı başarılı. Kullanılan model: "+model.trim()+
            " (sağlayıcı: "+name+"). Bu bilgi modelin kendi tahmini değil, "+
            "MusaCAD sunucusunun yanıt üstverisidir.";
    }

    private static String normalize(String raw) {
        String q=(raw==null?"":raw).toLowerCase(new Locale("tr","TR"));
        return Normalizer.normalize(q,Normalizer.Form.NFD)
            .replaceAll("\\p{M}+","").replace('ı','i')
            .replaceAll("\\s+"," ").trim();
    }

    private static boolean contains(String text,String... fragments) {
        for(String f:fragments)if(text.contains(f))return true;
        return false;
    }
}
